name: signals_lint_example
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  signals:
    path: ../../signals

dev_dependencies:
  signals_lint:
    path: ../
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

dependency_overrides:
  signals:
    path: ../../signals
  signals_core:
    path: ../../signals_core
  signals_flutter:
    path: ../../signals_flutter
  signals_hooks:
    path: ../../signals_hooks
  preact_signals:
    path: ../../preact_signals
  signals_lint:
    path: ../
