analyzer:
  errors:
    invalid_use_of_internal_member: ignore
include: package:flutter_lints/flutter.yaml

linter:
  rules:
    - public_member_api_docs
    - require_trailing_commas
    - prefer_relative_imports
formatter:
  trailing_commas: preserve
