version: 2
updates:
  # Maintain GitHub Actions dependencies
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  # Maintain Dart dependencies in the root workspace
  - package-ecosystem: "pub"
    directory: "/"
    schedule:
      interval: "weekly"
