name: signals

packages:
  - examples/*
  - packages/*

command:
  bootstrap:
    usePubspecOverrides: false
  version:
    # Generates precise changelogs based on conventional commits
    updateGitTagRefs: true
  publish:
    # Explicitly targets pub.dev (or a private hosted registry)
    registry: https://pub.dev
