include: package:very_good_analysis/analysis_options.yaml

linter:
  rules:
    public_member_api_docs: false
    document_ignores: false
analyzer:
  errors:
    deprecated_member_use: ignore
    void_checks: ignore
    avoid_types_as_parameter_names: ignore
    avoid_positional_boolean_parameters: ignore
    lines_longer_than_80_chars: ignore
    avoid_catches_without_on_clauses: ignore
    sort_pub_dependencies: ignore
