// GENERATED FILE - DO NOT EDIT MANUALLY
// Generated by scripts/generate_docs.dart

import 'package:jaspr/dom.dart';
import 'package:jaspr/jaspr.dart';
import 'package:jaspr_content/components/sidebar.dart' hide Sidebar;
import 'package:jaspr_content/components/sidebar_toggle_button.dart';
import 'package:jaspr_content/jaspr_content.dart';

class DynamicHeader extends StatelessComponent {
  const DynamicHeader({
    required this.logo,
    required this.title,
    this.items = const [],
    super.key,
  });

  final String logo;
  final String title;
  final List<Component> items;

  @override
  Component build(BuildContext context) {
    return Component.fragment([
      Document.head(children: [Style(styles: _styles)]),
      header(classes: 'header', [
        const SidebarToggleButton(),
        a(classes: 'header-title', href: '/', [
          img(src: logo, alt: 'Logo'),
          span([Component.text(title)]),
        ]),
        div(classes: 'header-content', [
          div(classes: 'header-items', items),
        ]),
      ]),
    ]);
  }

  static List<StyleRule> get _styles => [
    css('.docs .header-container').styles(
      raw: {
        'backdrop-filter': 'none !important',
        '-webkit-backdrop-filter': 'none !important',
        'background-color': 'var(--background) !important',
      },
    ),
    css('.header', [
      css('&').styles(
        height: 4.rem,
        display: Display.flex,
        alignItems: AlignItems.center,
        gap: Gap.column(1.rem),
        padding: Padding.symmetric(horizontal: 1.rem, vertical: .25.rem),
        margin: Margin.symmetric(horizontal: Unit.auto),
        border: Border.only(
          bottom: BorderSide(color: Color('#0000000d'), width: 1.px),
        ),
      ),
      css.media(MediaQuery.all(minWidth: 768.px), [
        css('&').styles(padding: Padding.symmetric(horizontal: 2.5.rem))
      ]),
      css('.header-title', [
        css('&').styles(
          display: Display.inlineFlex,
          flex: Flex(basis: 15.rem),
          alignItems: AlignItems.center,
          gap: Gap.column(.75.rem),
          textDecoration: TextDecoration.none,
          raw: {'color': 'inherit'},
        ),
        css('img').styles(
          height: 1.5.rem,
          width: Unit.auto,
          raw: {
            'filter': 'brightness(0.3) contrast(1.3) saturate(1.5)',
          },
        ),
        css('span').styles(fontWeight: FontWeight.w700),
      ]),
      css('.header-content', [
        css('&').styles(
          display: Display.flex,
          flex: Flex(grow: 1),
          justifyContent: JustifyContent.end,
          alignItems: AlignItems.center,
        ),
      ]),
      css('.header-items', [
        css('&').styles(
          display: Display.flex,
          alignItems: AlignItems.center,
          gap: Gap.column(0.5.rem),
        ),
      ]),
    ]),
    css('[data-theme="dark"] .header .header-title img, html.dark .header .header-title img', [
      css('&').styles(
        raw: {
          'filter': 'none',
        },
      ),
    ]),
  ];
}

class DynamicSidebar extends StatelessComponent {
  const DynamicSidebar({super.key});

  @override
  Component build(BuildContext context) {
    final currentUrl = context.page.url;
    print('DEBUG: DynamicSidebar currentUrl = "$currentUrl"');

    // 1. Guides Section
    if (!currentUrl.startsWith('/packages/')) {
      return Sidebar(
        groups: [
          const SidebarGroup(
            links: [
              SidebarLink(text: "Overview", href: '/'),
            ],
          ),
          const SidebarGroup(
            title: 'Reference',
            links: [
              SidebarLink(text: "Overview", href: '/reference/overview'),
              SidebarLink(text: "Installing", href: '/reference/install'),
              SidebarLink(text: "AI Integration", href: '/reference/ai'),
            ],
          ),
          const SidebarGroup(
            title: 'Guides',
            links: [
              SidebarLink(text: "Persisted Signals", href: '/guides/persisted-signals'),
              SidebarLink(text: "Dependency Injection", href: '/guides/dependency-injection'),
              SidebarLink(text: "Bi-directional Data Flow", href: '/guides/bi-directional-data-flow'),
              SidebarLink(text: "Value Notifier", href: '/guides/value-notifier'),
            ],
          ),
        ],
      );
    }

    // 2. Preact Signals Section
    if (currentUrl.startsWith('/packages/preact_signals')) {
      return const Sidebar(
        groups: [
          SidebarGroup(
            links: [
              SidebarLink(text: "Overview & Index", href: '/packages/preact_signals/'),
            ],
          ),

          SidebarGroup(
            title: 'Core Primitives',
            links: [
              SidebarLink(text: "Action", href: '/packages/preact_signals/core/action'),
              SidebarLink(text: "Batch", href: '/packages/preact_signals/core/batch'),
              SidebarLink(text: "Computed", href: '/packages/preact_signals/core/computed'),
              SidebarLink(text: "Effect", href: '/packages/preact_signals/core/effect'),
              SidebarLink(text: "ReadonlySignal", href: '/packages/preact_signals/core/readonly'),
              SidebarLink(text: "Signal", href: '/packages/preact_signals/core/signal'),
              SidebarLink(text: "Untracked", href: '/packages/preact_signals/core/untracked'),
            ],
          ),
          SidebarGroup(
            title: 'Utilities',
            links: [
              SidebarLink(text: "Model", href: '/packages/preact_signals/utilities/model'),
              SidebarLink(text: "SignalEquality", href: '/packages/preact_signals/utilities/equality'),
            ],
          ),
        ],
      );
    }

    // 3. Signals Core Section
    if (currentUrl.startsWith('/packages/signals_core')) {
      return const Sidebar(
        groups: [
          SidebarGroup(
            links: [
              SidebarLink(text: "Overview & Index", href: '/packages/signals_core/'),
            ],
          ),

          SidebarGroup(
            title: 'Core Primitives',
            links: [
              SidebarLink(text: "Action", href: '/packages/signals_core/core/action'),
              SidebarLink(text: "Batch", href: '/packages/signals_core/core/batch'),
              SidebarLink(text: "Computed", href: '/packages/signals_core/core/computed'),
              SidebarLink(text: "Effect", href: '/packages/signals_core/core/effect'),
              SidebarLink(text: "LinkedSignal", href: '/packages/signals_core/core/linked-signal'),
              SidebarLink(text: "ReadonlySignal", href: '/packages/signals_core/core/readonly'),
              SidebarLink(text: "Signal", href: '/packages/signals_core/core/signal'),
              SidebarLink(text: "Untracked", href: '/packages/signals_core/core/untracked'),
            ],
          ),
          SidebarGroup(
            title: 'Reactive Collections',
            links: [
              SidebarLink(text: "ChangeStackSignal", href: '/packages/signals_core/value/change-stack'),
              SidebarLink(text: "IterableSignal", href: '/packages/signals_core/value/iterable'),
              SidebarLink(text: "ListSignal", href: '/packages/signals_core/value/list'),
              SidebarLink(text: "MapSignal", href: '/packages/signals_core/value/map'),
              SidebarLink(text: "SetSignal", href: '/packages/signals_core/value/set'),
            ],
          ),
          SidebarGroup(
            title: 'Reactive Mixins',
            links: [
              SidebarLink(text: "ChangeStackSignalMixin", href: '/packages/signals_core/mixins/change-stack'),
              SidebarLink(text: "EventSinkSignalMixin", href: '/packages/signals_core/mixins/event-sink'),
              SidebarLink(text: "IterableSignalMixin", href: '/packages/signals_core/mixins/iterable'),
              SidebarLink(text: "ListSignalMixin", href: '/packages/signals_core/mixins/list'),
              SidebarLink(text: "MapSignalMixin", href: '/packages/signals_core/mixins/map'),
              SidebarLink(text: "QueueSignalMixin", href: '/packages/signals_core/mixins/queue'),
              SidebarLink(text: "SetSignalMixin", href: '/packages/signals_core/mixins/set'),
              SidebarLink(text: "SinkSignalMixin", href: '/packages/signals_core/mixins/sink'),
              SidebarLink(text: "StreamSignalMixin", href: '/packages/signals_core/mixins/stream'),
              SidebarLink(text: "TrackedSignalMixin", href: '/packages/signals_core/mixins/tracked'),
            ],
          ),
          SidebarGroup(
            title: 'Async Primitives',
            links: [
              SidebarLink(text: "AsyncState", href: '/packages/signals_core/async/state'),
              SidebarLink(text: "AsyncSignal", href: '/packages/signals_core/async/signal'),
              SidebarLink(text: "Computed", href: '/packages/signals_core/async/computed'),
              SidebarLink(text: "Connect", href: '/packages/signals_core/async/connect'),
              SidebarLink(text: "Future", href: '/packages/signals_core/async/future'),
              SidebarLink(text: "StreamSignal", href: '/packages/signals_core/async/stream'),
            ],
          ),
          SidebarGroup(
            title: 'Utilities',
            links: [
              SidebarLink(text: "Model", href: '/packages/signals_core/utilities/model'),
              SidebarLink(text: "PersistedSignal", href: '/packages/signals_core/utilities/persisted'),
              SidebarLink(text: "SignalContainer", href: '/packages/signals_core/utilities/container'),
              SidebarLink(text: "SignalEquality", href: '/packages/signals_core/utilities/equality'),
              SidebarLink(text: "SignalsObserver", href: '/packages/signals_core/utilities/observer'),
            ],
          ),
        ],
      );
    }

    // 4. Signals Flutter Section
    if (currentUrl.startsWith('/packages/signals_flutter')) {
      return const Sidebar(
        groups: [
          SidebarGroup(
            links: [
              SidebarLink(text: "Overview & Index", href: '/packages/signals_flutter/'),
            ],
          ),

          SidebarGroup(
            title: 'Core Primitives',
            links: [
              SidebarLink(text: "Action", href: '/packages/signals_flutter/core/action'),
              SidebarLink(text: "Batch", href: '/packages/signals_flutter/core/batch'),
              SidebarLink(text: "Computed", href: '/packages/signals_flutter/core/computed'),
              SidebarLink(text: "Effect", href: '/packages/signals_flutter/core/effect'),
              SidebarLink(text: "LinkedSignal", href: '/packages/signals_flutter/core/linked-signal'),
              SidebarLink(text: "ReadonlySignal", href: '/packages/signals_flutter/core/readonly'),
              SidebarLink(text: "Signal", href: '/packages/signals_flutter/core/signal'),
              SidebarLink(text: "Untracked", href: '/packages/signals_flutter/core/untracked'),
            ],
          ),
          SidebarGroup(
            title: 'Reactive Collections',
            links: [
              SidebarLink(text: "ChangeStackSignal", href: '/packages/signals_flutter/value/change-stack'),
              SidebarLink(text: "IterableSignal", href: '/packages/signals_flutter/value/iterable'),
              SidebarLink(text: "ListSignal", href: '/packages/signals_flutter/value/list'),
              SidebarLink(text: "MapSignal", href: '/packages/signals_flutter/value/map'),
              SidebarLink(text: "SetSignal", href: '/packages/signals_flutter/value/set'),
            ],
          ),
          SidebarGroup(
            title: 'Reactive Mixins',
            links: [
              SidebarLink(text: "ChangeStackSignalMixin", href: '/packages/signals_flutter/mixins/change-stack'),
              SidebarLink(text: "EventSinkSignalMixin", href: '/packages/signals_flutter/mixins/event-sink'),
              SidebarLink(text: "IterableSignalMixin", href: '/packages/signals_flutter/mixins/iterable'),
              SidebarLink(text: "ListSignalMixin", href: '/packages/signals_flutter/mixins/list'),
              SidebarLink(text: "MapSignalMixin", href: '/packages/signals_flutter/mixins/map'),
              SidebarLink(text: "QueueSignalMixin", href: '/packages/signals_flutter/mixins/queue'),
              SidebarLink(text: "SetSignalMixin", href: '/packages/signals_flutter/mixins/set'),
              SidebarLink(text: "SinkSignalMixin", href: '/packages/signals_flutter/mixins/sink'),
              SidebarLink(text: "StreamSignalMixin", href: '/packages/signals_flutter/mixins/stream'),
              SidebarLink(text: "TrackedSignalMixin", href: '/packages/signals_flutter/mixins/tracked'),
            ],
          ),
          SidebarGroup(
            title: 'Async Primitives',
            links: [
              SidebarLink(text: "AsyncState", href: '/packages/signals_flutter/async/state'),
              SidebarLink(text: "AsyncSignal", href: '/packages/signals_flutter/async/signal'),
              SidebarLink(text: "Computed", href: '/packages/signals_flutter/async/computed'),
              SidebarLink(text: "Connect", href: '/packages/signals_flutter/async/connect'),
              SidebarLink(text: "Future", href: '/packages/signals_flutter/async/future'),
              SidebarLink(text: "Stream", href: '/packages/signals_flutter/async/stream'),
            ],
          ),
          SidebarGroup(
            title: 'Utilities',
            links: [
              SidebarLink(text: "Model", href: '/packages/signals_flutter/utilities/model'),
              SidebarLink(text: "PersistedSignal", href: '/packages/signals_flutter/utilities/persisted'),
              SidebarLink(text: "SignalContainer", href: '/packages/signals_flutter/utilities/container'),
              SidebarLink(text: "SignalEquality", href: '/packages/signals_flutter/utilities/equality'),
              SidebarLink(text: "SignalsObserver", href: '/packages/signals_flutter/utilities/observer'),
            ],
          ),
          SidebarGroup(
            title: 'Flutter Components',
            links: [
              SidebarLink(text: "FlutterComputed", href: '/packages/signals_flutter/flutter/computed'),
              SidebarLink(text: "SignalAnimatedBuilder", href: '/packages/signals_flutter/flutter/watch'),
              SidebarLink(text: "FlutterSignal", href: '/packages/signals_flutter/flutter/signal'),
              SidebarLink(text: "SignalProvider", href: '/packages/signals_flutter/flutter/signal-provider'),
              SidebarLink(text: "SignalsMixin", href: '/packages/signals_flutter/flutter/signals-mixin'),
              SidebarLink(text: "Value Listenable", href: '/packages/signals_flutter/flutter/value-listenable'),
              SidebarLink(text: "Value Notifier", href: '/packages/signals_flutter/flutter/value-notifier'),
            ],
          ),
        ],
      );
    }

    // 5. Signals Hooks Section
    if (currentUrl.startsWith('/packages/signals_hooks')) {
      return const Sidebar(
        groups: [
          SidebarGroup(
            links: [
              SidebarLink(text: "Overview & Index", href: '/packages/signals_hooks/'),
            ],
          ),

          SidebarGroup(
            title: 'Hooks',
            links: [
              SidebarLink(text: "useAsyncComputed", href: '/packages/signals_hooks/hooks/use-async-computed'),
              SidebarLink(text: "useAsyncSignal", href: '/packages/signals_hooks/hooks/use-async-signal'),
              SidebarLink(text: "useChangeStackSignal", href: '/packages/signals_hooks/hooks/use-change-stack-signal'),
              SidebarLink(text: "useComputed", href: '/packages/signals_hooks/hooks/use-computed'),
              SidebarLink(text: "useConnect", href: '/packages/signals_hooks/hooks/use-connect'),
              SidebarLink(text: "useExistingSignal", href: '/packages/signals_hooks/hooks/use-existing-signal'),
              SidebarLink(text: "useFutureSignal", href: '/packages/signals_hooks/hooks/use-future-signal'),
              SidebarLink(text: "useIterableSignal", href: '/packages/signals_hooks/hooks/use-iterable-signal'),
              SidebarLink(text: "useLazySignal", href: '/packages/signals_hooks/hooks/use-lazy-signal'),
              SidebarLink(text: "useLinkedSignal", href: '/packages/signals_hooks/hooks/use-linked-signal'),
              SidebarLink(text: "useListSignal", href: '/packages/signals_hooks/hooks/use-list-signal'),
              SidebarLink(text: "useMapSignal", href: '/packages/signals_hooks/hooks/use-map-signal'),
              SidebarLink(text: "useQueueSignal", href: '/packages/signals_hooks/hooks/use-queue-signal'),
              SidebarLink(text: "useSetSignal", href: '/packages/signals_hooks/hooks/use-set-signal'),
              SidebarLink(text: "useSignal", href: '/packages/signals_hooks/hooks/use-signal'),
              SidebarLink(text: "useSignalEffect", href: '/packages/signals_hooks/hooks/use-signal-effect'),
              SidebarLink(text: "useSignalValue", href: '/packages/signals_hooks/hooks/use-signal-value'),
              SidebarLink(text: "useStreamSignal", href: '/packages/signals_hooks/hooks/use-stream-signal'),
              SidebarLink(text: "useTrackedSignal", href: '/packages/signals_hooks/hooks/use-tracked-signal'),
              SidebarLink(text: "useValueListenableToSignal", href: '/packages/signals_hooks/hooks/use-value-listenable-to-signal'),
              SidebarLink(text: "useValueNotifierToSignal", href: '/packages/signals_hooks/hooks/use-value-notifier-to-signal'),
            ],
          ),
          SidebarGroup(
            title: 'Widgets',
            links: [
              SidebarLink(text: "SignalHookBuilder", href: '/packages/signals_hooks/widgets/signal-hook-builder'),
              SidebarLink(text: "SignalHookWidget", href: '/packages/signals_hooks/widgets/signal-hook-widget'),
            ],
          ),
        ],
      );
    }

    // 5.1. Signals DevTools Extension Section
    if (currentUrl.startsWith('/packages/signals_devtools_extension')) {
      return const Sidebar(
        groups: [
          SidebarGroup(
            links: [
              SidebarLink(text: "Overview & Index", href: '/packages/signals_devtools_extension/'),
            ],
          ),

          SidebarGroup(
            title: 'Flutter Components',
            links: [
              SidebarLink(text: "SignalsDevToolsExtension", href: '/packages/signals_devtools_extension/flutter/devtools'),
            ],
          ),
        ],
      );
    }

    // 5.2. Signals Lint Section
    if (currentUrl.startsWith('/packages/signals_lint')) {
      return const Sidebar(
        groups: [
          SidebarGroup(
            links: [
              SidebarLink(text: "Overview & Index", href: '/packages/signals_lint/'),
            ],
          ),

          SidebarGroup(
            title: 'Flutter Components',
            links: [
              SidebarLink(text: "ConvertStatefulToSignalStatefulWidget", href: '/packages/signals_lint/flutter/convert-stateful-to-signal-stateful-widget'),
              SidebarLink(text: "ConvertStatelessToSignalWidget", href: '/packages/signals_lint/flutter/convert-stateless-to-signal-widget'),
              SidebarLink(text: "MigrateSignalsMixinToSignalStatefulWidget", href: '/packages/signals_lint/flutter/migrate-signals-mixin-to-signal-stateful-widget'),
              SidebarLink(text: "MigrateWatchToSignalBuilder", href: '/packages/signals_lint/flutter/migrate-watch-to-signal-builder'),
              SidebarLink(text: "SignalsAvoidCreateInBuildMethod", href: '/packages/signals_lint/flutter/signals-avoid-create-in-build-method'),
              SidebarLink(text: "SignalsAvoidDeprecatedSignalsMixin", href: '/packages/signals_lint/flutter/signals-avoid-deprecated-signals-mixin'),
              SidebarLink(text: "SignalsAvoidDeprecatedWatchExtension", href: '/packages/signals_lint/flutter/signals-avoid-deprecated-watch-extension'),
              SidebarLink(text: "SignalsPreferNamedBuilder", href: '/packages/signals_lint/flutter/signals-prefer-named-builder'),
              SidebarLink(text: "SignalsPreferUnifiedOptions", href: '/packages/signals_lint/flutter/signals-prefer-unified-options'),
              SidebarLink(text: "WrapWithSignalBuilder", href: '/packages/signals_lint/flutter/wrap-with-signal-builder'),
            ],
          ),
        ],
      );
    }

    // 6. Unified Signals Section
    if (currentUrl.startsWith('/packages/signals')) {
      return const Sidebar(
        groups: [
          SidebarGroup(
            links: [
              SidebarLink(text: "Overview & Index", href: '/packages/signals/'),
            ],
          ),

          SidebarGroup(
            title: 'Core Primitives',
            links: [
              SidebarLink(text: "Action", href: '/packages/signals/core/action'),
              SidebarLink(text: "Batch", href: '/packages/signals/core/batch'),
              SidebarLink(text: "Computed", href: '/packages/signals/core/computed'),
              SidebarLink(text: "Effect", href: '/packages/signals/core/effect'),
              SidebarLink(text: "LinkedSignal", href: '/packages/signals/core/linked-signal'),
              SidebarLink(text: "ReadonlySignal", href: '/packages/signals/core/readonly'),
              SidebarLink(text: "Signal", href: '/packages/signals/core/signal'),
              SidebarLink(text: "Untracked", href: '/packages/signals/core/untracked'),
            ],
          ),
          SidebarGroup(
            title: 'Reactive Collections',
            links: [
              SidebarLink(text: "ChangeStackSignal", href: '/packages/signals/value/change-stack'),
              SidebarLink(text: "IterableSignal", href: '/packages/signals/value/iterable'),
              SidebarLink(text: "ListSignal", href: '/packages/signals/value/list'),
              SidebarLink(text: "MapSignal", href: '/packages/signals/value/map'),
              SidebarLink(text: "SetSignal", href: '/packages/signals/value/set'),
            ],
          ),
          SidebarGroup(
            title: 'Reactive Mixins',
            links: [
              SidebarLink(text: "ChangeStackSignalMixin", href: '/packages/signals/mixins/change-stack'),
              SidebarLink(text: "EventSinkSignalMixin", href: '/packages/signals/mixins/event-sink'),
              SidebarLink(text: "IterableSignalMixin", href: '/packages/signals/mixins/iterable'),
              SidebarLink(text: "ListSignalMixin", href: '/packages/signals/mixins/list'),
              SidebarLink(text: "MapSignalMixin", href: '/packages/signals/mixins/map'),
              SidebarLink(text: "QueueSignalMixin", href: '/packages/signals/mixins/queue'),
              SidebarLink(text: "SetSignalMixin", href: '/packages/signals/mixins/set'),
              SidebarLink(text: "SinkSignalMixin", href: '/packages/signals/mixins/sink'),
              SidebarLink(text: "StreamSignalMixin", href: '/packages/signals/mixins/stream'),
              SidebarLink(text: "TrackedSignalMixin", href: '/packages/signals/mixins/tracked'),
            ],
          ),
          SidebarGroup(
            title: 'Async Primitives',
            links: [
              SidebarLink(text: "AsyncState", href: '/packages/signals/async/state'),
              SidebarLink(text: "AsyncSignal", href: '/packages/signals/async/signal'),
              SidebarLink(text: "Computed", href: '/packages/signals/async/computed'),
              SidebarLink(text: "Connect", href: '/packages/signals/async/connect'),
              SidebarLink(text: "FutureSignal", href: '/packages/signals/async/future'),
              SidebarLink(text: "Stream", href: '/packages/signals/async/stream'),
            ],
          ),
          SidebarGroup(
            title: 'Utilities',
            links: [
              SidebarLink(text: "Model", href: '/packages/signals/utilities/model'),
              SidebarLink(text: "PersistedSignal", href: '/packages/signals/utilities/persisted'),
              SidebarLink(text: "SignalContainer", href: '/packages/signals/utilities/container'),
              SidebarLink(text: "SignalEquality", href: '/packages/signals/utilities/equality'),
              SidebarLink(text: "SignalsObserver", href: '/packages/signals/utilities/observer'),
            ],
          ),
          SidebarGroup(
            title: 'Flutter Components',
            links: [
              SidebarLink(text: "FlutterComputed", href: '/packages/signals/flutter/computed'),
              SidebarLink(text: "SignalAnimatedBuilder", href: '/packages/signals/flutter/watch'),
              SidebarLink(text: "FlutterSignal", href: '/packages/signals/flutter/signal'),
              SidebarLink(text: "SignalProvider", href: '/packages/signals/flutter/signal-provider'),
              SidebarLink(text: "SignalsMixin", href: '/packages/signals/flutter/signals-mixin'),
              SidebarLink(text: "Value Listenable", href: '/packages/signals/flutter/value-listenable'),
              SidebarLink(text: "Value Notifier", href: '/packages/signals/flutter/value-notifier'),
            ],
          ),
        ],
      );
    }

    // Fallback Sidebar
    return const Sidebar(
      groups: [],
    );
  }
}

class Sidebar extends StatelessComponent {
  const Sidebar({this.currentRoute, required this.groups, super.key});

  final String? currentRoute;
  final List<SidebarGroup> groups;

  @override
  Component build(BuildContext context) {
    final currentUrl = currentRoute ?? context.page.url;

    String activePackageUrl;
    if (currentUrl.startsWith('/packages/signals_flutter')) {
      activePackageUrl = '/packages/signals_flutter';
    } else if (currentUrl.startsWith('/packages/signals_core')) {
      activePackageUrl = '/packages/signals_core';
    } else if (currentUrl.startsWith('/packages/preact_signals')) {
      activePackageUrl = '/packages/preact_signals';
    } else if (currentUrl.startsWith('/packages/signals_hooks')) {
      activePackageUrl = '/packages/signals_hooks';
    } else if (currentUrl.startsWith('/packages/signals_devtools_extension')) {
      activePackageUrl = '/packages/signals_devtools_extension';
    } else if (currentUrl.startsWith('/packages/signals_lint')) {
      activePackageUrl = '/packages/signals_lint';
    } else if (currentUrl.startsWith('/packages/signals')) {
      activePackageUrl = '/packages/signals';
    } else {
      activePackageUrl = '/';
    }

    return Component.fragment([
      Document.head(children: [Style(styles: _styles)]),
      nav(classes: 'sidebar', [
        button(classes: 'sidebar-close', [
          span([Component.text('✕')]),
        ]),
        select(
          classes: 'package-switcher',
          value: activePackageUrl,
          attributes: {
            'onchange': 'window.location.href = this.value',
          },
          [
            option(
              value: '/',
              selected: currentUrl == '/' || currentUrl.startsWith('/guides/') || currentUrl.startsWith('/reference/'),
              [Component.text('📖 Guides & Overview')],
            ),
            option(
              value: '/packages/signals',
              selected: currentUrl == '/packages/signals' || currentUrl.startsWith('/packages/signals/'),
              [Component.text('📦 signals')],
            ),
            option(
              value: '/packages/signals_flutter',
              selected: currentUrl == '/packages/signals_flutter' || currentUrl.startsWith('/packages/signals_flutter/'),
              [Component.text('📱 signals_flutter')],
            ),
            option(
              value: '/packages/signals_core',
              selected: currentUrl == '/packages/signals_core' || currentUrl.startsWith('/packages/signals_core/'),
              [Component.text('⚡ signals_core')],
            ),
            option(
              value: '/packages/preact_signals',
              selected: currentUrl == '/packages/preact_signals' || currentUrl.startsWith('/packages/preact_signals/'),
              [Component.text('⚛️ preact_signals')],
            ),
            option(
              value: '/packages/signals_hooks',
              selected: currentUrl == '/packages/signals_hooks' || currentUrl.startsWith('/packages/signals_hooks/'),
              [Component.text('🪝 signals_hooks')],
            ),
            option(
              value: '/packages/signals_devtools_extension',
              selected: currentUrl == '/packages/signals_devtools_extension' || currentUrl.startsWith('/packages/signals_devtools_extension/'),
              [Component.text('🛠️ signals_devtools')],
            ),
            option(
              value: '/packages/signals_lint',
              selected: currentUrl == '/packages/signals_lint' || currentUrl.startsWith('/packages/signals_lint/'),
              [Component.text('🔍 signals_lint')],
            ),
          ],
        ),
        div([
          for (final group in groups)
            div(classes: 'sidebar-group', [
              if (group.title case final groupTitle?) h3([Component.text(groupTitle)]),
              ul([
                for (final item in group.links)
                  li([
                    div(classes: currentUrl == item.href ? 'active' : null, [
                      a(href: item.href, [Component.text(item.text)]),
                    ]),
                  ]),
              ]),
            ]),
        ]),
      ]),
    ]);
  }

  static List<StyleRule> get _styles => [
    css('.sidebar', [
      css('&').styles(
        position: Position.relative(),
        fontSize: 0.875.rem,
        lineHeight: 1.25.rem,
        padding: Padding.only(left: 0.5.rem, bottom: 1.25.rem, top: 0.75.rem),
      ),
      css.media(MediaQuery.all(minWidth: 1024.px), [css('&').styles(padding: Padding.only(top: Unit.zero))]),
      css('.sidebar-close', [
        css('&').styles(
          position: Position.absolute(top: 0.75.rem, right: 0.75.rem),
        ),
        css.media(MediaQuery.all(minWidth: 1024.px), [css('&').styles(display: Display.none)]),
      ]),
      css('.sidebar-group', [
        css('&').styles(
          padding: Padding.only(top: 1.5.rem, right: 0.75.rem),
        ),
        css('h3').styles(
          fontWeight: FontWeight.w600,
          fontSize: 14.px,
          padding: Padding.only(left: 0.75.rem),
          margin: Margin.only(bottom: 1.rem, top: Unit.zero),
        ),
        css('ul').styles(listStyle: ListStyle.none, margin: Margin.zero, padding: Padding.zero),
        css('li', [
          css('div', [
            css('&').styles(
              opacity: 0.75,
              margin: Margin.only(bottom: 1.px),
              whiteSpace: WhiteSpace.noWrap,
              overflow: Overflow.hidden,
              textOverflow: TextOverflow.ellipsis,
              radius: BorderRadius.circular(.375.rem),
              display: Display.flex,
              transition: Transition('all', duration: 150.ms, curve: Curve.easeInOut),
            ),
            css('&:hover').styles(opacity: 1, backgroundColor: Color('#0000000d')),
            css('&.active').styles(
              opacity: 1,
              color: Color('#3b82f6'),
              fontWeight: FontWeight.w700,
              backgroundColor: Color('color-mix(in srgb, currentColor 15%, transparent)'),
            ),
          ]),
          css('a').styles(
            padding: Padding.only(left: 12.px, top: .5.rem, bottom: .5.rem),
            display: Display.inlineFlex,
            flex: Flex(grow: 1),
          ),
        ]),
      ]),
    ]),
    css('.package-switcher', [
      css('&').styles(
        display: Display.block,
        margin: Margin.only(top: 1.5.rem, bottom: 1.rem, left: 1.rem, right: 1.rem),
        padding: Padding.only(top: 0.625.rem, bottom: 0.625.rem, left: 1.rem, right: 2.5.rem),
        fontSize: 0.875.rem,
        fontWeight: FontWeight.w600,
        radius: BorderRadius.circular(0.5.rem),
        cursor: Cursor.pointer,
        transition: Transition('all', duration: 150.ms, curve: Curve.easeInOut),
        raw: {
          'width': 'calc(100% - 2rem)',
          'appearance': 'none',
          '-webkit-appearance': 'none',
          'background-image': 'url("data:image/svg+xml;charset=utf-8,%3Csvg xmlns=\'http://www.w3.org/2000/svg\' fill=\'none\' viewBox=\'0 0 20 20\'%3E%3Cpath stroke=\'%2364748b\' stroke-linecap=\'round\' stroke-linejoin=\'round\' stroke-width=\'1.5\' d=\'m6 8 4 4 4-4\'/%3E%3C/svg%3E")',
          'background-position': 'right 0.75rem center',
          'background-repeat': 'no-repeat',
          'background-size': '1.25rem',
          'border': '1px solid var(--border, #e2e8f0)',
          'background-color': 'var(--bg-card, #ffffff)',
          'color': 'var(--text, #0f172a)',
        },
      ),
      css('&:hover').styles(
        raw: {
          'border-color': '#cbd5e1',
          'background-color': '#f8fafc',
        },
      ),
      css('&:focus').styles(
        raw: {
          'border-color': '#3b82f6',
          'box-shadow': '0 0 0 2px rgba(59, 130, 246, 0.15)',
        },
      ),
    ]),
    css('[data-theme="dark"] .package-switcher, html.dark .package-switcher', [
      css('&').styles(
        raw: {
          'border-color': '#475569',
          'background-color': '#1e293b',
          'color': '#f8fafc',
        },
      ),
      css('&:hover').styles(
        raw: {
          'border-color': '#64748b',
          'background-color': '#0f172a',
        },
      ),
      css('&:focus').styles(
        raw: {
          'border-color': '#3b82f6',
        },
      ),
    ]),
    css('[data-theme="dark"] .package-switcher option, html.dark .package-switcher option', [
      css('&').styles(
        raw: {
          'background-color': '#1e293b',
          'color': '#f8fafc',
        },
      ),
    ]),
  ];
}

