// GENERATED FILE - DO NOT EDIT MANUALLY
// Generated by scripts/generate_docs.dart

import 'package:jaspr/dom.dart';
import 'package:jaspr/jaspr.dart';
import 'package:jaspr_content/components/sidebar.dart' hide Sidebar;
import 'package:jaspr_content/components/sidebar_toggle_button.dart';
import 'package:jaspr_content/jaspr_content.dart';

class DynamicHeader extends StatelessComponent {
  const DynamicHeader({
    required this.logo,
    required this.title,
    this.items = const [],
    super.key,
  });

  final String logo;
  final String title;
  final List<Component> items;

  @override
  Component build(BuildContext context) {
    return Component.fragment([
      Document.head(children: [Style(styles: _styles)]),
      header(classes: 'header', [
        const SidebarToggleButton(),
        a(classes: 'header-title', href: '/', [
          img(src: logo, alt: 'Logo'),
          span([Component.text(title)]),
        ]),
        div(classes: 'header-content', [
          div(classes: 'header-items', items),
        ]),
      ]),
    ]);
  }

  static List<StyleRule> get _styles => [
    css('.docs .header-container').styles(
      raw: {
        'backdrop-filter': 'none !important',
        '-webkit-backdrop-filter': 'none !important',
        'background-color': 'var(--background) !important',
      },
    ),
    css('.header', [
      css('&').styles(
        height: 4.rem,
        display: Display.flex,
        alignItems: AlignItems.center,
        gap: Gap.column(1.rem),
        padding: Padding.symmetric(horizontal: 1.rem, vertical: .25.rem),
        margin: Margin.symmetric(horizontal: Unit.auto),
        border: Border.only(
          bottom: BorderSide(color: Color('#0000000d'), width: 1.px),
        ),
      ),
      css.media(MediaQuery.all(minWidth: 768.px), [
        css('&').styles(padding: Padding.symmetric(horizontal: 2.5.rem))
      ]),
      css('.header-title', [
        css('&').styles(
          display: Display.inlineFlex,
          flex: Flex(basis: 15.rem),
          alignItems: AlignItems.center,
          gap: Gap.column(.75.rem),
          textDecoration: TextDecoration.none,
          raw: {'color': 'inherit'},
        ),
        css('img').styles(
          height: 1.5.rem,
          width: Unit.auto,
          raw: {
            'filter': 'brightness(0.3) contrast(1.3) saturate(1.5)',
          },
        ),
        css('span').styles(fontWeight: FontWeight.w700),
      ]),
      css('.header-content', [
        css('&').styles(
          display: Display.flex,
          flex: Flex(grow: 1),
          justifyContent: JustifyContent.end,
          alignItems: AlignItems.center,
        ),
      ]),
      css('.header-items', [
        css('&').styles(
          display: Display.flex,
          alignItems: AlignItems.center,
          gap: Gap.column(0.5.rem),
        ),
      ]),
    ]),
    css('[data-theme="dark"] .header .header-title img, html.dark .header .header-title img', [
      css('&').styles(
        raw: {
          'filter': 'none',
        },
      ),
    ]),
    css('.deprecated-badge').styles(
      raw: {
        'font-size': '10px',
        'font-weight': '700',
        'text-transform': 'uppercase',
        'color': '#ef4444',
        'background-color': '#fef2f2',
        'border': '1px solid #fca5a5',
        'border-radius': '4px',
        'padding': '1px 6px',
        'margin-left': '8px',
        'display': 'inline-flex',
        'align-items': 'center',
        'justify-content': 'center',
        'line-height': '1',
        'vertical-align': 'middle',
      },
    ),
    css('html.dark .deprecated-badge, [data-theme="dark"] .deprecated-badge').styles(
      raw: {
        'color': '#fca5a5',
        'background-color': '#7f1d1d',
        'border-color': '#991b1b',
      },
    ),
    css('.sidebar-container a[href="/packages/signals_core/utilities/observer"]::after, .sidebar a[href="/packages/signals_core/utilities/observer"]::after').styles(
      raw: {
        'content': '"deprecated"',
        'font-size': '8px',
        'font-weight': '700',
        'text-transform': 'uppercase',
        'color': '#ef4444',
        'background-color': '#fef2f2',
        'border': '1px solid #fca5a5',
        'border-radius': '4px',
        'padding': '0 5px',
        'margin-left': '8px',
        'display': 'inline-flex',
        'align-items': 'center',
        'justify-content': 'center',
        'line-height': '1',
        'height': '14px',
      },
    ),
    css('html.dark .sidebar-container a[href="/packages/signals_core/utilities/observer"]::after, html.dark .sidebar a[href="/packages/signals_core/utilities/observer"]::after, [data-theme="dark"] .sidebar a[href="/packages/signals_core/utilities/observer"]::after').styles(
      raw: {
        'color': '#fca5a5',
        'background-color': '#7f1d1d',
        'border-color': '#991b1b',
      },
    ),
    css('.sidebar-container a[href="/packages/signals_flutter/utilities/observer"]::after, .sidebar a[href="/packages/signals_flutter/utilities/observer"]::after').styles(
      raw: {
        'content': '"deprecated"',
        'font-size': '8px',
        'font-weight': '700',
        'text-transform': 'uppercase',
        'color': '#ef4444',
        'background-color': '#fef2f2',
        'border': '1px solid #fca5a5',
        'border-radius': '4px',
        'padding': '0 5px',
        'margin-left': '8px',
        'display': 'inline-flex',
        'align-items': 'center',
        'justify-content': 'center',
        'line-height': '1',
        'height': '14px',
      },
    ),
    css('html.dark .sidebar-container a[href="/packages/signals_flutter/utilities/observer"]::after, html.dark .sidebar a[href="/packages/signals_flutter/utilities/observer"]::after, [data-theme="dark"] .sidebar a[href="/packages/signals_flutter/utilities/observer"]::after').styles(
      raw: {
        'color': '#fca5a5',
        'background-color': '#7f1d1d',
        'border-color': '#991b1b',
      },
    ),
    css('.sidebar-container a[href="/packages/signals_flutter/mixins/signals-mixin"]::after, .sidebar a[href="/packages/signals_flutter/mixins/signals-mixin"]::after').styles(
      raw: {
        'content': '"deprecated"',
        'font-size': '8px',
        'font-weight': '700',
        'text-transform': 'uppercase',
        'color': '#ef4444',
        'background-color': '#fef2f2',
        'border': '1px solid #fca5a5',
        'border-radius': '4px',
        'padding': '0 5px',
        'margin-left': '8px',
        'display': 'inline-flex',
        'align-items': 'center',
        'justify-content': 'center',
        'line-height': '1',
        'height': '14px',
      },
    ),
    css('html.dark .sidebar-container a[href="/packages/signals_flutter/mixins/signals-mixin"]::after, html.dark .sidebar a[href="/packages/signals_flutter/mixins/signals-mixin"]::after, [data-theme="dark"] .sidebar a[href="/packages/signals_flutter/mixins/signals-mixin"]::after').styles(
      raw: {
        'color': '#fca5a5',
        'background-color': '#7f1d1d',
        'border-color': '#991b1b',
      },
    ),
    css('.sidebar-container a[href="/packages/signals_flutter/widgets/watch"]::after, .sidebar a[href="/packages/signals_flutter/widgets/watch"]::after').styles(
      raw: {
        'content': '"deprecated"',
        'font-size': '8px',
        'font-weight': '700',
        'text-transform': 'uppercase',
        'color': '#ef4444',
        'background-color': '#fef2f2',
        'border': '1px solid #fca5a5',
        'border-radius': '4px',
        'padding': '0 5px',
        'margin-left': '8px',
        'display': 'inline-flex',
        'align-items': 'center',
        'justify-content': 'center',
        'line-height': '1',
        'height': '14px',
      },
    ),
    css('html.dark .sidebar-container a[href="/packages/signals_flutter/widgets/watch"]::after, html.dark .sidebar a[href="/packages/signals_flutter/widgets/watch"]::after, [data-theme="dark"] .sidebar a[href="/packages/signals_flutter/widgets/watch"]::after').styles(
      raw: {
        'color': '#fca5a5',
        'background-color': '#7f1d1d',
        'border-color': '#991b1b',
      },
    ),
    css('.sidebar-container a[href="/packages/signals_flutter/widgets/watch-builder"]::after, .sidebar a[href="/packages/signals_flutter/widgets/watch-builder"]::after').styles(
      raw: {
        'content': '"deprecated"',
        'font-size': '8px',
        'font-weight': '700',
        'text-transform': 'uppercase',
        'color': '#ef4444',
        'background-color': '#fef2f2',
        'border': '1px solid #fca5a5',
        'border-radius': '4px',
        'padding': '0 5px',
        'margin-left': '8px',
        'display': 'inline-flex',
        'align-items': 'center',
        'justify-content': 'center',
        'line-height': '1',
        'height': '14px',
      },
    ),
    css('html.dark .sidebar-container a[href="/packages/signals_flutter/widgets/watch-builder"]::after, html.dark .sidebar a[href="/packages/signals_flutter/widgets/watch-builder"]::after, [data-theme="dark"] .sidebar a[href="/packages/signals_flutter/widgets/watch-builder"]::after').styles(
      raw: {
        'color': '#fca5a5',
        'background-color': '#7f1d1d',
        'border-color': '#991b1b',
      },
    ),
    css('.sidebar-container a[href="/packages/signals/utilities/observer"]::after, .sidebar a[href="/packages/signals/utilities/observer"]::after').styles(
      raw: {
        'content': '"deprecated"',
        'font-size': '8px',
        'font-weight': '700',
        'text-transform': 'uppercase',
        'color': '#ef4444',
        'background-color': '#fef2f2',
        'border': '1px solid #fca5a5',
        'border-radius': '4px',
        'padding': '0 5px',
        'margin-left': '8px',
        'display': 'inline-flex',
        'align-items': 'center',
        'justify-content': 'center',
        'line-height': '1',
        'height': '14px',
      },
    ),
    css('html.dark .sidebar-container a[href="/packages/signals/utilities/observer"]::after, html.dark .sidebar a[href="/packages/signals/utilities/observer"]::after, [data-theme="dark"] .sidebar a[href="/packages/signals/utilities/observer"]::after').styles(
      raw: {
        'color': '#fca5a5',
        'background-color': '#7f1d1d',
        'border-color': '#991b1b',
      },
    ),
    css('.sidebar-container a[href="/packages/signals/mixins/signals-mixin"]::after, .sidebar a[href="/packages/signals/mixins/signals-mixin"]::after').styles(
      raw: {
        'content': '"deprecated"',
        'font-size': '8px',
        'font-weight': '700',
        'text-transform': 'uppercase',
        'color': '#ef4444',
        'background-color': '#fef2f2',
        'border': '1px solid #fca5a5',
        'border-radius': '4px',
        'padding': '0 5px',
        'margin-left': '8px',
        'display': 'inline-flex',
        'align-items': 'center',
        'justify-content': 'center',
        'line-height': '1',
        'height': '14px',
      },
    ),
    css('html.dark .sidebar-container a[href="/packages/signals/mixins/signals-mixin"]::after, html.dark .sidebar a[href="/packages/signals/mixins/signals-mixin"]::after, [data-theme="dark"] .sidebar a[href="/packages/signals/mixins/signals-mixin"]::after').styles(
      raw: {
        'color': '#fca5a5',
        'background-color': '#7f1d1d',
        'border-color': '#991b1b',
      },
    ),
    css('.sidebar-container a[href="/packages/signals/widgets/watch"]::after, .sidebar a[href="/packages/signals/widgets/watch"]::after').styles(
      raw: {
        'content': '"deprecated"',
        'font-size': '8px',
        'font-weight': '700',
        'text-transform': 'uppercase',
        'color': '#ef4444',
        'background-color': '#fef2f2',
        'border': '1px solid #fca5a5',
        'border-radius': '4px',
        'padding': '0 5px',
        'margin-left': '8px',
        'display': 'inline-flex',
        'align-items': 'center',
        'justify-content': 'center',
        'line-height': '1',
        'height': '14px',
      },
    ),
    css('html.dark .sidebar-container a[href="/packages/signals/widgets/watch"]::after, html.dark .sidebar a[href="/packages/signals/widgets/watch"]::after, [data-theme="dark"] .sidebar a[href="/packages/signals/widgets/watch"]::after').styles(
      raw: {
        'color': '#fca5a5',
        'background-color': '#7f1d1d',
        'border-color': '#991b1b',
      },
    ),
    css('.sidebar-container a[href="/packages/signals/widgets/watch-builder"]::after, .sidebar a[href="/packages/signals/widgets/watch-builder"]::after').styles(
      raw: {
        'content': '"deprecated"',
        'font-size': '8px',
        'font-weight': '700',
        'text-transform': 'uppercase',
        'color': '#ef4444',
        'background-color': '#fef2f2',
        'border': '1px solid #fca5a5',
        'border-radius': '4px',
        'padding': '0 5px',
        'margin-left': '8px',
        'display': 'inline-flex',
        'align-items': 'center',
        'justify-content': 'center',
        'line-height': '1',
        'height': '14px',
      },
    ),
    css('html.dark .sidebar-container a[href="/packages/signals/widgets/watch-builder"]::after, html.dark .sidebar a[href="/packages/signals/widgets/watch-builder"]::after, [data-theme="dark"] .sidebar a[href="/packages/signals/widgets/watch-builder"]::after').styles(
      raw: {
        'color': '#fca5a5',
        'background-color': '#7f1d1d',
        'border-color': '#991b1b',
      },
    ),
    css('.sidebar-container a[href="/types/reloadsignalsdevtools"]::after, .sidebar a[href="/types/reloadsignalsdevtools"]::after').styles(
      raw: {
        'content': '"deprecated"',
        'font-size': '8px',
        'font-weight': '700',
        'text-transform': 'uppercase',
        'color': '#ef4444',
        'background-color': '#fef2f2',
        'border': '1px solid #fca5a5',
        'border-radius': '4px',
        'padding': '0 5px',
        'margin-left': '8px',
        'display': 'inline-flex',
        'align-items': 'center',
        'justify-content': 'center',
        'line-height': '1',
        'height': '14px',
      },
    ),
    css('html.dark .sidebar-container a[href="/types/reloadsignalsdevtools"]::after, html.dark .sidebar a[href="/types/reloadsignalsdevtools"]::after, [data-theme="dark"] .sidebar a[href="/types/reloadsignalsdevtools"]::after').styles(
      raw: {
        'color': '#fca5a5',
        'background-color': '#7f1d1d',
        'border-color': '#991b1b',
      },
    ),
    css('.sidebar-container a[href="/types/disablesignalsdevtools"]::after, .sidebar a[href="/types/disablesignalsdevtools"]::after').styles(
      raw: {
        'content': '"deprecated"',
        'font-size': '8px',
        'font-weight': '700',
        'text-transform': 'uppercase',
        'color': '#ef4444',
        'background-color': '#fef2f2',
        'border': '1px solid #fca5a5',
        'border-radius': '4px',
        'padding': '0 5px',
        'margin-left': '8px',
        'display': 'inline-flex',
        'align-items': 'center',
        'justify-content': 'center',
        'line-height': '1',
        'height': '14px',
      },
    ),
    css('html.dark .sidebar-container a[href="/types/disablesignalsdevtools"]::after, html.dark .sidebar a[href="/types/disablesignalsdevtools"]::after, [data-theme="dark"] .sidebar a[href="/types/disablesignalsdevtools"]::after').styles(
      raw: {
        'color': '#fca5a5',
        'background-color': '#7f1d1d',
        'border-color': '#991b1b',
      },
    ),
    css('.sidebar-container a[href="/types/signalsdevtoolsenabled"]::after, .sidebar a[href="/types/signalsdevtoolsenabled"]::after').styles(
      raw: {
        'content': '"deprecated"',
        'font-size': '8px',
        'font-weight': '700',
        'text-transform': 'uppercase',
        'color': '#ef4444',
        'background-color': '#fef2f2',
        'border': '1px solid #fca5a5',
        'border-radius': '4px',
        'padding': '0 5px',
        'margin-left': '8px',
        'display': 'inline-flex',
        'align-items': 'center',
        'justify-content': 'center',
        'line-height': '1',
        'height': '14px',
      },
    ),
    css('html.dark .sidebar-container a[href="/types/signalsdevtoolsenabled"]::after, html.dark .sidebar a[href="/types/signalsdevtoolsenabled"]::after, [data-theme="dark"] .sidebar a[href="/types/signalsdevtoolsenabled"]::after').styles(
      raw: {
        'color': '#fca5a5',
        'background-color': '#7f1d1d',
        'border-color': '#991b1b',
      },
    ),
    css('.sidebar-container a[href="/types/devtoolssignalsobserver"]::after, .sidebar a[href="/types/devtoolssignalsobserver"]::after').styles(
      raw: {
        'content': '"deprecated"',
        'font-size': '8px',
        'font-weight': '700',
        'text-transform': 'uppercase',
        'color': '#ef4444',
        'background-color': '#fef2f2',
        'border': '1px solid #fca5a5',
        'border-radius': '4px',
        'padding': '0 5px',
        'margin-left': '8px',
        'display': 'inline-flex',
        'align-items': 'center',
        'justify-content': 'center',
        'line-height': '1',
        'height': '14px',
      },
    ),
    css('html.dark .sidebar-container a[href="/types/devtoolssignalsobserver"]::after, html.dark .sidebar a[href="/types/devtoolssignalsobserver"]::after, [data-theme="dark"] .sidebar a[href="/types/devtoolssignalsobserver"]::after').styles(
      raw: {
        'color': '#fca5a5',
        'background-color': '#7f1d1d',
        'border-color': '#991b1b',
      },
    ),
    css('.sidebar-container a[href="/types/watch"]::after, .sidebar a[href="/types/watch"]::after').styles(
      raw: {
        'content': '"deprecated"',
        'font-size': '8px',
        'font-weight': '700',
        'text-transform': 'uppercase',
        'color': '#ef4444',
        'background-color': '#fef2f2',
        'border': '1px solid #fca5a5',
        'border-radius': '4px',
        'padding': '0 5px',
        'margin-left': '8px',
        'display': 'inline-flex',
        'align-items': 'center',
        'justify-content': 'center',
        'line-height': '1',
        'height': '14px',
      },
    ),
    css('html.dark .sidebar-container a[href="/types/watch"]::after, html.dark .sidebar a[href="/types/watch"]::after, [data-theme="dark"] .sidebar a[href="/types/watch"]::after').styles(
      raw: {
        'color': '#fca5a5',
        'background-color': '#7f1d1d',
        'border-color': '#991b1b',
      },
    ),
    css('.sidebar-container a[href="/types/watchbuilder"]::after, .sidebar a[href="/types/watchbuilder"]::after').styles(
      raw: {
        'content': '"deprecated"',
        'font-size': '8px',
        'font-weight': '700',
        'text-transform': 'uppercase',
        'color': '#ef4444',
        'background-color': '#fef2f2',
        'border': '1px solid #fca5a5',
        'border-radius': '4px',
        'padding': '0 5px',
        'margin-left': '8px',
        'display': 'inline-flex',
        'align-items': 'center',
        'justify-content': 'center',
        'line-height': '1',
        'height': '14px',
      },
    ),
    css('html.dark .sidebar-container a[href="/types/watchbuilder"]::after, html.dark .sidebar a[href="/types/watchbuilder"]::after, [data-theme="dark"] .sidebar a[href="/types/watchbuilder"]::after').styles(
      raw: {
        'color': '#fca5a5',
        'background-color': '#7f1d1d',
        'border-color': '#991b1b',
      },
    ),
    css('.sidebar-container a[href="/types/signalsmixin"]::after, .sidebar a[href="/types/signalsmixin"]::after').styles(
      raw: {
        'content': '"deprecated"',
        'font-size': '8px',
        'font-weight': '700',
        'text-transform': 'uppercase',
        'color': '#ef4444',
        'background-color': '#fef2f2',
        'border': '1px solid #fca5a5',
        'border-radius': '4px',
        'padding': '0 5px',
        'margin-left': '8px',
        'display': 'inline-flex',
        'align-items': 'center',
        'justify-content': 'center',
        'line-height': '1',
        'height': '14px',
      },
    ),
    css('html.dark .sidebar-container a[href="/types/signalsmixin"]::after, html.dark .sidebar a[href="/types/signalsmixin"]::after, [data-theme="dark"] .sidebar a[href="/types/signalsmixin"]::after').styles(
      raw: {
        'color': '#fca5a5',
        'background-color': '#7f1d1d',
        'border-color': '#991b1b',
      },
    ),
  ];
}

class DynamicSidebar extends StatelessComponent {
  const DynamicSidebar({super.key});

  @override
  Component build(BuildContext context) {
    final currentUrl = context.page.url;

    // 1a. Types Section
    if (currentUrl.startsWith('/types/')) {
      return Sidebar(
        groups: [
          SidebarGroup(
            links: [
              SidebarLink(text: "← Back to Overview", href: '/'),
            ],
          ),
          SidebarGroup(
            title: 'Types Reference',
            links: [

              SidebarLink(text: 'action', href: '/types/action'),
              SidebarLink(text: 'action0', href: '/types/action0'),
              SidebarLink(text: 'action1', href: '/types/action1'),
              SidebarLink(text: 'action10', href: '/types/action10'),
              SidebarLink(text: 'action2', href: '/types/action2'),
              SidebarLink(text: 'action3', href: '/types/action3'),
              SidebarLink(text: 'action4', href: '/types/action4'),
              SidebarLink(text: 'action5', href: '/types/action5'),
              SidebarLink(text: 'action6', href: '/types/action6'),
              SidebarLink(text: 'action7', href: '/types/action7'),
              SidebarLink(text: 'action8', href: '/types/action8'),
              SidebarLink(text: 'action9', href: '/types/action9'),
              SidebarLink(text: 'ActionExt0', href: '/types/actionext0'),
              SidebarLink(text: 'ActionExt1', href: '/types/actionext1'),
              SidebarLink(text: 'ActionExt10', href: '/types/actionext10'),
              SidebarLink(text: 'ActionExt2', href: '/types/actionext2'),
              SidebarLink(text: 'ActionExt3', href: '/types/actionext3'),
              SidebarLink(text: 'ActionExt4', href: '/types/actionext4'),
              SidebarLink(text: 'ActionExt5', href: '/types/actionext5'),
              SidebarLink(text: 'ActionExt6', href: '/types/actionext6'),
              SidebarLink(text: 'ActionExt7', href: '/types/actionext7'),
              SidebarLink(text: 'ActionExt8', href: '/types/actionext8'),
              SidebarLink(text: 'ActionExt9', href: '/types/actionext9'),
              SidebarLink(text: 'AsyncData', href: '/types/asyncdata'),
              SidebarLink(text: 'AsyncDataRefreshing', href: '/types/asyncdatarefreshing'),
              SidebarLink(text: 'AsyncDataReloading', href: '/types/asyncdatareloading'),
              SidebarLink(text: 'AsyncError', href: '/types/asyncerror'),
              SidebarLink(text: 'AsyncErrorRefreshing', href: '/types/asyncerrorrefreshing'),
              SidebarLink(text: 'AsyncErrorReloading', href: '/types/asyncerrorreloading'),
              SidebarLink(text: 'AsyncLoading', href: '/types/asyncloading'),
              SidebarLink(text: 'AsyncSignal', href: '/types/asyncsignal'),
              SidebarLink(text: 'AsyncSignalOptions', href: '/types/asyncsignaloptions'),
              SidebarLink(text: 'AsyncSignalState', href: '/types/asyncsignalstate'),
              SidebarLink(text: 'AsyncState', href: '/types/asyncstate'),
              SidebarLink(text: 'batch', href: '/types/batch'),
              SidebarLink(text: 'BoolSignalExtension', href: '/types/boolsignalextension'),
              SidebarLink(text: 'ChangeSignalOptions', href: '/types/changesignaloptions'),
              SidebarLink(text: 'changeStack', href: '/types/changestack'),
              SidebarLink(text: 'ChangeStackSignal', href: '/types/changestacksignal'),
              SidebarLink(text: 'ChangeStackSignalMixin', href: '/types/changestacksignalmixin'),
              SidebarLink(text: 'ComparableSignalExtension', href: '/types/comparablesignalextension'),
              SidebarLink(text: 'Computed', href: '/types/computed'),
              SidebarLink(text: 'computedAsync', href: '/types/computedasync'),
              SidebarLink(text: 'computedContainer', href: '/types/computedcontainer'),
              SidebarLink(text: 'computedFrom', href: '/types/computedfrom'),
              SidebarLink(text: 'ComputedOptions', href: '/types/computedoptions'),
              SidebarLink(text: 'Connect', href: '/types/connect'),
              SidebarLink(text: 'ConvertedSignalStatefulElement', href: '/types/convertedsignalstatefulelement'),
              SidebarLink(text: 'ConvertedSignalStatefulWidget', href: '/types/convertedsignalstatefulwidget'),
              SidebarLink(text: 'ConvertedSignalWidget', href: '/types/convertedsignalwidget'),
              SidebarLink(text: 'createModel', href: '/types/createmodel'),
              SidebarLink(text: 'DevToolsSignalsObserver', href: '/types/devtoolssignalsobserver'),
              SidebarLink(text: 'disableSignalsDevTools', href: '/types/disablesignalsdevtools'),
              SidebarLink(text: 'DoubleSignalExtension', href: '/types/doublesignalextension'),
              SidebarLink(text: 'Effect', href: '/types/effect'),
              SidebarLink(text: 'EffectCycleDetectionError', href: '/types/effectcycledetectionerror'),
              SidebarLink(text: 'EffectOptions', href: '/types/effectoptions'),
              SidebarLink(text: 'EnumSignalExtension', href: '/types/enumsignalextension'),
              SidebarLink(text: 'EventSinkSignalMixin', href: '/types/eventsinksignalmixin'),
              SidebarLink(text: 'FlutterComputed', href: '/types/fluttercomputed'),
              SidebarLink(text: 'FlutterReadonlySignal', href: '/types/flutterreadonlysignal'),
              SidebarLink(text: 'FlutterReadonlySignalUtils', href: '/types/flutterreadonlysignalutils'),
              SidebarLink(text: 'FlutterSignal', href: '/types/fluttersignal'),
              SidebarLink(text: 'FutureSignal', href: '/types/futuresignal'),
              SidebarLink(text: 'futureSignalContainer', href: '/types/futuresignalcontainer'),
              SidebarLink(text: 'IntSignalExtension', href: '/types/intsignalextension'),
              SidebarLink(text: 'IterableSignal', href: '/types/iterablesignal'),
              SidebarLink(text: 'IterableSignalMixin', href: '/types/iterablesignalmixin'),
              SidebarLink(text: 'IterableSignalOptions', href: '/types/iterablesignaloptions'),
              SidebarLink(text: 'lazySignal', href: '/types/lazysignal'),
              SidebarLink(text: 'LazySignalInitializationError', href: '/types/lazysignalinitializationerror'),
              SidebarLink(text: 'LinkedSignal', href: '/types/linkedsignal'),
              SidebarLink(text: 'LinkedSignalOptions', href: '/types/linkedsignaloptions'),
              SidebarLink(text: 'LinkedSignalPreviousState', href: '/types/linkedsignalpreviousstate'),
              SidebarLink(text: 'ListSignal', href: '/types/listsignal'),
              SidebarLink(text: 'ListSignalExtension', href: '/types/listsignalextension'),
              SidebarLink(text: 'ListSignalMixin', href: '/types/listsignalmixin'),
              SidebarLink(text: 'ListSignalOptions', href: '/types/listsignaloptions'),
              SidebarLink(text: 'LoggingSignalsObserver', href: '/types/loggingsignalsobserver'),
              SidebarLink(text: 'MapSignal', href: '/types/mapsignal'),
              SidebarLink(text: 'MapSignalExtension', href: '/types/mapsignalextension'),
              SidebarLink(text: 'MapSignalMixin', href: '/types/mapsignalmixin'),
              SidebarLink(text: 'MapSignalOptions', href: '/types/mapsignaloptions'),
              SidebarLink(text: 'MultiSignalProvider', href: '/types/multisignalprovider'),
              SidebarLink(text: 'NumSignalExtension', href: '/types/numsignalextension'),
              SidebarLink(text: 'onSignalRead', href: '/types/onsignalread'),
              SidebarLink(text: 'PatternSignalExtension', href: '/types/patternsignalextension'),
              SidebarLink(text: 'PersistedBoolSignal', href: '/types/persistedboolsignal'),
              SidebarLink(text: 'PersistedDoubleSignal', href: '/types/persisteddoublesignal'),
              SidebarLink(text: 'PersistedEnumSignal', href: '/types/persistedenumsignal'),
              SidebarLink(text: 'PersistedIntSignal', href: '/types/persistedintsignal'),
              SidebarLink(text: 'PersistedNullableBoolSignal', href: '/types/persistednullableboolsignal'),
              SidebarLink(text: 'PersistedNullableDoubleSignal', href: '/types/persistednullabledoublesignal'),
              SidebarLink(text: 'PersistedNullableEnumSignal', href: '/types/persistednullableenumsignal'),
              SidebarLink(text: 'PersistedNullableIntSignal', href: '/types/persistednullableintsignal'),
              SidebarLink(text: 'PersistedNullableNumSignal', href: '/types/persistednullablenumsignal'),
              SidebarLink(text: 'PersistedNullableStringSignal', href: '/types/persistednullablestringsignal'),
              SidebarLink(text: 'PersistedNumSignal', href: '/types/persistednumsignal'),
              SidebarLink(text: 'PersistedSignal', href: '/types/persistedsignal'),
              SidebarLink(text: 'PersistedSignalMixin', href: '/types/persistedsignalmixin'),
              SidebarLink(text: 'PersistedSignalOptions', href: '/types/persistedsignaloptions'),
              SidebarLink(text: 'PersistedStringSignal', href: '/types/persistedstringsignal'),
              SidebarLink(text: 'QueueSignal', href: '/types/queuesignal'),
              SidebarLink(text: 'QueueSignalMixin', href: '/types/queuesignalmixin'),
              SidebarLink(text: 'QueueSignalOptions', href: '/types/queuesignaloptions'),
              SidebarLink(text: 'readonly', href: '/types/readonly'),
              SidebarLink(text: 'ReadonlyIterableSignalExtension', href: '/types/readonlyiterablesignalextension'),
              SidebarLink(text: 'ReadonlyListSignalExtension', href: '/types/readonlylistsignalextension'),
              SidebarLink(text: 'ReadonlyMapSignalExtension', href: '/types/readonlymapsignalextension'),
              SidebarLink(text: 'ReadonlySetSignalExtension', href: '/types/readonlysetsignalextension'),
              SidebarLink(text: 'ReadonlySignal', href: '/types/readonlysignal'),
              SidebarLink(text: 'readonlySignalContainer', href: '/types/readonlysignalcontainer'),
              SidebarLink(text: 'ReadonlySignalMixin', href: '/types/readonlysignalmixin'),
              SidebarLink(text: 'ReadonlySignalOptions', href: '/types/readonlysignaloptions'),
              SidebarLink(text: 'ReadonlySignalUtils', href: '/types/readonlysignalutils'),
              SidebarLink(text: 'reloadSignalsDevTools', href: '/types/reloadsignalsdevtools'),
              SidebarLink(text: 'RenderSignalBox', href: '/types/rendersignalbox'),
              SidebarLink(text: 'RenderSignalCustomPaint', href: '/types/rendersignalcustompaint'),
              SidebarLink(text: 'RenderSignalProxyBox', href: '/types/rendersignalproxybox'),
              SidebarLink(text: 'SetSignal', href: '/types/setsignal'),
              SidebarLink(text: 'SetSignalExtension', href: '/types/setsignalextension'),
              SidebarLink(text: 'SetSignalMixin', href: '/types/setsignalmixin'),
              SidebarLink(text: 'SetSignalOptions', href: '/types/setsignaloptions'),
              SidebarLink(text: 'Signal', href: '/types/signal'),
              SidebarLink(text: 'SignalAnimatedBuilder', href: '/types/signalanimatedbuilder'),
              SidebarLink(text: 'SignalBoolExtensions', href: '/types/signalboolextensions'),
              SidebarLink(text: 'SignalBuilder', href: '/types/signalbuilder'),
              SidebarLink(text: 'SignalComparableExtensions', href: '/types/signalcomparableextensions'),
              SidebarLink(text: 'SignalContainer', href: '/types/signalcontainer'),
              SidebarLink(text: 'SignalCustomEquality', href: '/types/signalcustomequality'),
              SidebarLink(text: 'SignalCustomPaint', href: '/types/signalcustompaint'),
              SidebarLink(text: 'SignalCustomPainter', href: '/types/signalcustompainter'),
              SidebarLink(text: 'SignalDeepEquality', href: '/types/signaldeepequality'),
              SidebarLink(text: 'SignalDoubleExtensions', href: '/types/signaldoubleextensions'),
              SidebarLink(text: 'SignalEffect', href: '/types/signaleffect'),
              SidebarLink(text: 'SignalEffectException', href: '/types/signaleffectexception'),
              SidebarLink(text: 'SignalElement', href: '/types/signalelement'),
              SidebarLink(text: 'SignalEnumExtensions', href: '/types/signalenumextensions'),
              SidebarLink(text: 'SignalEquality', href: '/types/signalequality'),
              SidebarLink(text: 'SignalFunctionExtensions', href: '/types/signalfunctionextensions'),
              SidebarLink(text: 'SignalFutureUtils', href: '/types/signalfutureutils'),
              SidebarLink(text: 'SignalHookBuilder', href: '/types/signalhookbuilder'),
              SidebarLink(text: 'SignalHookWidget', href: '/types/signalhookwidget'),
              SidebarLink(text: 'SignalIdentityEquality', href: '/types/signalidentityequality'),
              SidebarLink(text: 'SignalIntExtensions', href: '/types/signalintextensions'),
              SidebarLink(text: 'SignalIterableExtensions', href: '/types/signaliterableextensions'),
              SidebarLink(text: 'SignalIterableUtils', href: '/types/signaliterableutils'),
              SidebarLink(text: 'SignalListExtensions', href: '/types/signallistextensions'),
              SidebarLink(text: 'SignalListUtils', href: '/types/signallistutils'),
              SidebarLink(text: 'SignalMapExtensions', href: '/types/signalmapextensions'),
              SidebarLink(text: 'SignalMapUtils', href: '/types/signalmaputils'),
              SidebarLink(text: 'SignalModel', href: '/types/signalmodel'),
              SidebarLink(text: 'SignalModelConstructor', href: '/types/signalmodelconstructor'),
              SidebarLink(text: 'SignalModelOptions', href: '/types/signalmodeloptions'),
              SidebarLink(text: 'SignalNumExtensions', href: '/types/signalnumextensions'),
              SidebarLink(text: 'SignalObjectUtils', href: '/types/signalobjectutils'),
              SidebarLink(text: 'SignalOptions', href: '/types/signaloptions'),
              SidebarLink(text: 'SignalOptionsBase', href: '/types/signaloptionsbase'),
              SidebarLink(text: 'SignalPainterWidget', href: '/types/signalpainterwidget'),
              SidebarLink(text: 'SignalPatternExtensions', href: '/types/signalpatternextensions'),
              SidebarLink(text: 'SignalProvider', href: '/types/signalprovider'),
              SidebarLink(text: 'SignalProxyWidget', href: '/types/signalproxywidget'),
              SidebarLink(text: 'SignalQueueUtils', href: '/types/signalqueueutils'),
              SidebarLink(text: 'SignalsAutoDisposeMixin', href: '/types/signalsautodisposemixin'),
              SidebarLink(text: 'signalsDevToolsEnabled', href: '/types/signalsdevtoolsenabled'),
              SidebarLink(text: 'SignalsError', href: '/types/signalserror'),
              SidebarLink(text: 'SignalSetExtensions', href: '/types/signalsetextensions'),
              SidebarLink(text: 'SignalSetUtils', href: '/types/signalsetutils'),
              SidebarLink(text: 'SignalsInMemoryKeyValueStore', href: '/types/signalsinmemorykeyvaluestore'),
              SidebarLink(text: 'SignalsKeyValueStore', href: '/types/signalskeyvaluestore'),
              SidebarLink(text: 'SignalsMixin', href: '/types/signalsmixin'),
              SidebarLink(text: 'SignalsObserver', href: '/types/signalsobserver'),
              SidebarLink(text: 'SignalsReadAfterDisposeError', href: '/types/signalsreadafterdisposeerror'),
              SidebarLink(text: 'SignalStandardEquality', href: '/types/signalstandardequality'),
              SidebarLink(text: 'SignalStatefulElement', href: '/types/signalstatefulelement'),
              SidebarLink(text: 'SignalStatefulHookWidget', href: '/types/signalstatefulhookwidget'),
              SidebarLink(text: 'SignalStatefulWidget', href: '/types/signalstatefulwidget'),
              SidebarLink(text: 'SignalStreamUtils', href: '/types/signalstreamutils'),
              SidebarLink(text: 'SignalStringExtensions', href: '/types/signalstringextensions'),
              SidebarLink(text: 'SignalsWriteAfterDisposeError', href: '/types/signalswriteafterdisposeerror'),
              SidebarLink(text: 'SignalValueListenableUtils', href: '/types/signalvaluelistenableutils'),
              SidebarLink(text: 'SignalValueNotifierUtils', href: '/types/signalvaluenotifierutils'),
              SidebarLink(text: 'SignalWidget', href: '/types/signalwidget'),
              SidebarLink(text: 'SinkSignalMixin', href: '/types/sinksignalmixin'),
              SidebarLink(text: 'StatefulElementConvertExtension', href: '/types/statefulelementconvertextension'),
              SidebarLink(text: 'StatefulWidgetConvertWidgetExtension', href: '/types/statefulwidgetconvertwidgetextension'),
              SidebarLink(text: 'StatelessElementConvertExtension', href: '/types/statelesselementconvertextension'),
              SidebarLink(text: 'StatelessWidgetConvertWidgetExtension', href: '/types/statelesswidgetconvertwidgetextension'),
              SidebarLink(text: 'StreamSignal', href: '/types/streamsignal'),
              SidebarLink(text: 'streamSignalContainer', href: '/types/streamsignalcontainer'),
              SidebarLink(text: 'StreamSignalMixin', href: '/types/streamsignalmixin'),
              SidebarLink(text: 'StringSignalExtension', href: '/types/stringsignalextension'),
              SidebarLink(text: 'TickerSignal', href: '/types/tickersignal'),
              SidebarLink(text: 'TimerSignal', href: '/types/timersignal'),
              SidebarLink(text: 'TimerSignalDurationUtils', href: '/types/timersignaldurationutils'),
              SidebarLink(text: 'TrackedSignal', href: '/types/trackedsignal'),
              SidebarLink(text: 'TrackedSignalMixin', href: '/types/trackedsignalmixin'),
              SidebarLink(text: 'TrackedSignalOptions', href: '/types/trackedsignaloptions'),
              SidebarLink(text: 'untracked', href: '/types/untracked'),
              SidebarLink(text: 'useAsyncComputed', href: '/types/useasynccomputed'),
              SidebarLink(text: 'useAsyncSignal', href: '/types/useasyncsignal'),
              SidebarLink(text: 'useChangeStackSignal', href: '/types/usechangestacksignal'),
              SidebarLink(text: 'useComputed', href: '/types/usecomputed'),
              SidebarLink(text: 'useConnect', href: '/types/useconnect'),
              SidebarLink(text: 'useExistingSignal', href: '/types/useexistingsignal'),
              SidebarLink(text: 'useFutureSignal', href: '/types/usefuturesignal'),
              SidebarLink(text: 'useIterableSignal', href: '/types/useiterablesignal'),
              SidebarLink(text: 'useLazySignal', href: '/types/uselazysignal'),
              SidebarLink(text: 'useLinkedSignal', href: '/types/uselinkedsignal'),
              SidebarLink(text: 'useListSignal', href: '/types/uselistsignal'),
              SidebarLink(text: 'useMapSignal', href: '/types/usemapsignal'),
              SidebarLink(text: 'useQueueSignal', href: '/types/usequeuesignal'),
              SidebarLink(text: 'useSetSignal', href: '/types/usesetsignal'),
              SidebarLink(text: 'useSignal', href: '/types/usesignal'),
              SidebarLink(text: 'useSignalEffect', href: '/types/usesignaleffect'),
              SidebarLink(text: 'useSignalProvider', href: '/types/usesignalprovider'),
              SidebarLink(text: 'useSignalValue', href: '/types/usesignalvalue'),
              SidebarLink(text: 'useStreamSignal', href: '/types/usestreamsignal'),
              SidebarLink(text: 'useTrackedSignal', href: '/types/usetrackedsignal'),
              SidebarLink(text: 'useValueListenableToSignal', href: '/types/usevaluelistenabletosignal'),
              SidebarLink(text: 'useValueNotifierToSignal', href: '/types/usevaluenotifiertosignal'),
              SidebarLink(text: 'ValueListenableSignalMixin', href: '/types/valuelistenablesignalmixin'),
              SidebarLink(text: 'valueListenableToSignal', href: '/types/valuelistenabletosignal'),
              SidebarLink(text: 'ValueNotifierSignalMixin', href: '/types/valuenotifiersignalmixin'),
              SidebarLink(text: 'valueNotifierToSignal', href: '/types/valuenotifiertosignal'),
              SidebarLink(text: 'Watch', href: '/types/watch'),
              SidebarLink(text: 'WatchBuilder', href: '/types/watchbuilder'),
              SidebarLink(text: 'WriteableSignalUtils', href: '/types/writeablesignalutils'),
            ],
          ),
        ],
      );
    }

    // 1. Guides Section
    if (!currentUrl.startsWith('/packages/')) {
      return Sidebar(
        groups: [
          const SidebarGroup(
            links: [
              SidebarLink(text: "Overview", href: '/'),
            ],
          ),
          const SidebarGroup(
            title: 'Reference',
            links: [
              SidebarLink(text: "Overview", href: '/reference/overview'),
              SidebarLink(text: "Installing", href: '/reference/install'),
              SidebarLink(text: "AI Integration", href: '/reference/ai'),
            ],
          ),
          const SidebarGroup(
            title: 'Guides',
            links: [
              SidebarLink(text: "Persisted Signals", href: '/guides/persisted-signals'),
              SidebarLink(text: "Dependency Injection", href: '/guides/dependency-injection'),
              SidebarLink(text: "Bi-directional Data Flow", href: '/guides/bi-directional-data-flow'),
              SidebarLink(text: "Value Notifier", href: '/guides/value-notifier'),
            ],
          ),
        ],
      );
    }

    // 2. Preact Signals Section
    if (currentUrl.startsWith('/packages/preact_signals')) {
      return const Sidebar(
        groups: [
          SidebarGroup(
            links: [
              SidebarLink(text: "Overview & Index", href: '/packages/preact_signals/'),
            ],
          ),

          SidebarGroup(
            title: 'Core Primitives',
            links: [
              SidebarLink(text: "Action", href: '/packages/preact_signals/core/action'),
              SidebarLink(text: "Batch", href: '/packages/preact_signals/core/batch'),
              SidebarLink(text: "Computed", href: '/packages/preact_signals/core/computed'),
              SidebarLink(text: "Signal", href: '/packages/preact_signals/core/signal'),
              SidebarLink(text: "Effect", href: '/packages/preact_signals/core/effect'),
              SidebarLink(text: "ReadonlySignal", href: '/packages/preact_signals/core/readonly'),
              SidebarLink(text: "Untracked", href: '/packages/preact_signals/core/untracked'),
            ],
          ),
          SidebarGroup(
            title: 'Utilities',
            links: [
              SidebarLink(text: "Model", href: '/packages/preact_signals/utilities/model'),
              SidebarLink(text: "SignalEquality", href: '/packages/preact_signals/utilities/equality'),
            ],
          ),
        ],
      );
    }

    // 3. Signals Core Section
    if (currentUrl.startsWith('/packages/signals_core')) {
      return const Sidebar(
        groups: [
          SidebarGroup(
            links: [
              SidebarLink(text: "Overview & Index", href: '/packages/signals_core/'),
            ],
          ),

          SidebarGroup(
            title: 'Core Primitives',
            links: [
              SidebarLink(text: "Action", href: '/packages/signals_core/core/action'),
              SidebarLink(text: "Batch", href: '/packages/signals_core/core/batch'),
              SidebarLink(text: "Signal", href: '/packages/signals_core/core/signal'),
              SidebarLink(text: "Computed", href: '/packages/signals_core/core/computed'),
              SidebarLink(text: "Effect", href: '/packages/signals_core/core/effect'),
              SidebarLink(text: "LinkedSignal", href: '/packages/signals_core/core/linked-signal'),
              SidebarLink(text: "ReadonlySignal", href: '/packages/signals_core/core/readonly'),
              SidebarLink(text: "Untracked", href: '/packages/signals_core/core/untracked'),
            ],
          ),
          SidebarGroup(
            title: 'Reactive Collections',
            links: [
              SidebarLink(text: "ChangeStackSignal", href: '/packages/signals_core/value/change-stack'),
              SidebarLink(text: "IterableSignal", href: '/packages/signals_core/value/iterable'),
              SidebarLink(text: "ListSignal", href: '/packages/signals_core/value/list'),
              SidebarLink(text: "MapSignal", href: '/packages/signals_core/value/map'),
              SidebarLink(text: "SetSignal", href: '/packages/signals_core/value/set'),
            ],
          ),
          SidebarGroup(
            title: 'Async Primitives',
            links: [
              SidebarLink(text: "AsyncState", href: '/packages/signals_core/async/state'),
              SidebarLink(text: "AsyncSignal", href: '/packages/signals_core/async/signal'),
              SidebarLink(text: "Computed", href: '/packages/signals_core/async/computed'),
              SidebarLink(text: "Connect", href: '/packages/signals_core/async/connect'),
              SidebarLink(text: "FutureSignal", href: '/packages/signals_core/async/future'),
              SidebarLink(text: "Stream", href: '/packages/signals_core/async/stream'),
            ],
          ),
          SidebarGroup(
            title: 'Reactive Mixins',
            links: [
              SidebarLink(text: "ChangeStackSignalMixin", href: '/packages/signals_core/mixins/change-stack'),
              SidebarLink(text: "EventSinkSignalMixin", href: '/packages/signals_core/mixins/event-sink'),
              SidebarLink(text: "IterableSignalMixin", href: '/packages/signals_core/mixins/iterable'),
              SidebarLink(text: "ListSignalMixin", href: '/packages/signals_core/mixins/list'),
              SidebarLink(text: "MapSignalMixin", href: '/packages/signals_core/mixins/map'),
              SidebarLink(text: "QueueSignalMixin", href: '/packages/signals_core/mixins/queue'),
              SidebarLink(text: "SetSignalMixin", href: '/packages/signals_core/mixins/set'),
              SidebarLink(text: "SinkSignalMixin", href: '/packages/signals_core/mixins/sink'),
              SidebarLink(text: "StreamSignalMixin", href: '/packages/signals_core/mixins/stream'),
              SidebarLink(text: "TrackedSignalMixin", href: '/packages/signals_core/mixins/tracked'),
            ],
          ),
          SidebarGroup(
            title: 'Utilities',
            links: [
              SidebarLink(text: "SignalContainer", href: '/packages/signals_core/utilities/container'),
              SidebarLink(text: "Model", href: '/packages/signals_core/utilities/model'),
              SidebarLink(text: "SignalsObserver", href: '/packages/signals_core/utilities/observer'),
              SidebarLink(text: "PersistedSignal", href: '/packages/signals_core/utilities/persisted'),
              SidebarLink(text: "SignalEquality", href: '/packages/signals_core/utilities/equality'),
            ],
          ),
        ],
      );
    }

    // 4. Signals Flutter Section
    if (currentUrl.startsWith('/packages/signals_flutter')) {
      return const Sidebar(
        groups: [
          SidebarGroup(
            links: [
              SidebarLink(text: "Overview & Index", href: '/packages/signals_flutter/'),
            ],
          ),

          SidebarGroup(
            title: 'Core Primitives',
            links: [
              SidebarLink(text: "Action", href: '/packages/signals_flutter/core/action'),
              SidebarLink(text: "Batch", href: '/packages/signals_flutter/core/batch'),
              SidebarLink(text: "Signal", href: '/packages/signals_flutter/core/signal'),
              SidebarLink(text: "Computed", href: '/packages/signals_flutter/core/computed'),
              SidebarLink(text: "Effect", href: '/packages/signals_flutter/core/effect'),
              SidebarLink(text: "LinkedSignal", href: '/packages/signals_flutter/core/linked-signal'),
              SidebarLink(text: "ReadonlySignal", href: '/packages/signals_flutter/core/readonly'),
              SidebarLink(text: "Untracked", href: '/packages/signals_flutter/core/untracked'),
            ],
          ),
          SidebarGroup(
            title: 'Reactive Collections',
            links: [
              SidebarLink(text: "ChangeStackSignal", href: '/packages/signals_flutter/value/change-stack'),
              SidebarLink(text: "IterableSignal", href: '/packages/signals_flutter/value/iterable'),
              SidebarLink(text: "ListSignal", href: '/packages/signals_flutter/value/list'),
              SidebarLink(text: "MapSignal", href: '/packages/signals_flutter/value/map'),
              SidebarLink(text: "SetSignal", href: '/packages/signals_flutter/value/set'),
            ],
          ),
          SidebarGroup(
            title: 'Async Primitives',
            links: [
              SidebarLink(text: "AsyncState", href: '/packages/signals_flutter/async/state'),
              SidebarLink(text: "AsyncSignal", href: '/packages/signals_flutter/async/signal'),
              SidebarLink(text: "Computed", href: '/packages/signals_flutter/async/computed'),
              SidebarLink(text: "Connect", href: '/packages/signals_flutter/async/connect'),
              SidebarLink(text: "FutureSignal", href: '/packages/signals_flutter/async/future'),
              SidebarLink(text: "Stream", href: '/packages/signals_flutter/async/stream'),
            ],
          ),
          SidebarGroup(
            title: 'Reactive Signals',
            links: [
              SidebarLink(text: "FlutterComputed", href: '/packages/signals_flutter/signals/flutter-computed'),
              SidebarLink(text: "Flutter Readonly Signal", href: '/packages/signals_flutter/signals/flutter-readonly-signal'),
              SidebarLink(text: "FlutterSignal", href: '/packages/signals_flutter/signals/flutter-signal'),
              SidebarLink(text: "Ticker Signal", href: '/packages/signals_flutter/signals/ticker-signal'),
            ],
          ),
          SidebarGroup(
            title: 'Flutter Widgets',
            links: [
              SidebarLink(text: "MultiSignalProvider", href: '/packages/signals_flutter/widgets/multi-signal-provider'),
              SidebarLink(text: "SignalAnimatedBuilder", href: '/packages/signals_flutter/widgets/signal-animated-builder'),
              SidebarLink(text: "SignalBuilder", href: '/packages/signals_flutter/widgets/signal-builder'),
              SidebarLink(text: "SignalCustomPaint", href: '/packages/signals_flutter/widgets/signal-custom-paint'),
              SidebarLink(text: "SignalPainterWidget", href: '/packages/signals_flutter/widgets/signal-painter-widget'),
              SidebarLink(text: "SignalProvider", href: '/packages/signals_flutter/widgets/signal-provider'),
              SidebarLink(text: "SignalProxyWidget", href: '/packages/signals_flutter/widgets/signal-proxy-widget'),
              SidebarLink(text: "SignalWidget", href: '/packages/signals_flutter/widgets/signal-widget'),
              SidebarLink(text: "Watch", href: '/packages/signals_flutter/widgets/watch'),
              SidebarLink(text: "WatchBuilder", href: '/packages/signals_flutter/widgets/watch-builder'),
            ],
          ),
          SidebarGroup(
            title: 'Reactive Mixins',
            links: [
              SidebarLink(text: "ChangeStackSignalMixin", href: '/packages/signals_flutter/mixins/change-stack'),
              SidebarLink(text: "EventSinkSignalMixin", href: '/packages/signals_flutter/mixins/event-sink'),
              SidebarLink(text: "IterableSignalMixin", href: '/packages/signals_flutter/mixins/iterable'),
              SidebarLink(text: "ListSignalMixin", href: '/packages/signals_flutter/mixins/list'),
              SidebarLink(text: "MapSignalMixin", href: '/packages/signals_flutter/mixins/map'),
              SidebarLink(text: "QueueSignalMixin", href: '/packages/signals_flutter/mixins/queue'),
              SidebarLink(text: "SetSignalMixin", href: '/packages/signals_flutter/mixins/set'),
              SidebarLink(text: "SignalsMixin", href: '/packages/signals_flutter/mixins/signals-mixin'),
              SidebarLink(text: "SinkSignalMixin", href: '/packages/signals_flutter/mixins/sink'),
              SidebarLink(text: "StreamSignalMixin", href: '/packages/signals_flutter/mixins/stream'),
              SidebarLink(text: "TrackedSignalMixin", href: '/packages/signals_flutter/mixins/tracked'),
              SidebarLink(text: "ValueListenableSignalMixin", href: '/packages/signals_flutter/mixins/value-listenable-signal-mixin'),
              SidebarLink(text: "ValueNotifierSignalMixin", href: '/packages/signals_flutter/mixins/value-notifier-signal-mixin'),
            ],
          ),
          SidebarGroup(
            title: 'Lifecycle & Effects',
            links: [
              SidebarLink(text: "SignalEffect", href: '/packages/signals_flutter/effects/signal-effect'),
            ],
          ),
          SidebarGroup(
            title: 'Low-Level Render Objects',
            links: [
              SidebarLink(text: "RenderSignalBox", href: '/packages/signals_flutter/render/render-signal-box'),
              SidebarLink(text: "RenderSignalCustomPaint", href: '/packages/signals_flutter/render/render-signal-custom-paint'),
              SidebarLink(text: "RenderSignalProxyBox", href: '/packages/signals_flutter/render/render-signal-proxy-box'),
            ],
          ),
          SidebarGroup(
            title: 'Widget & Context Extensions',
            links: [
              SidebarLink(text: "ConvertedSignalStatefulElement", href: '/packages/signals_flutter/extensions/converted-signal-stateful-element'),
              SidebarLink(text: "ConvertedSignalStatefulWidget", href: '/packages/signals_flutter/extensions/converted-signal-stateful-widget'),
              SidebarLink(text: "ConvertedSignalWidget", href: '/packages/signals_flutter/extensions/converted-signal-widget'),
              SidebarLink(text: "SignalCustomPainter", href: '/packages/signals_flutter/extensions/signal-custom-painter'),
              SidebarLink(text: "SignalElement", href: '/packages/signals_flutter/extensions/signal-element'),
              SidebarLink(text: "SignalStatefulElement", href: '/packages/signals_flutter/extensions/signal-stateful-element'),
              SidebarLink(text: "SignalStatefulWidget", href: '/packages/signals_flutter/extensions/signal-stateful-widget'),
              SidebarLink(text: "Signal Value Listenable Utils", href: '/packages/signals_flutter/extensions/signal-value-listenable-utils'),
              SidebarLink(text: "Signal Value Notifier Utils", href: '/packages/signals_flutter/extensions/signal-value-notifier-utils'),
              SidebarLink(text: "Stateful Element Convert Extension", href: '/packages/signals_flutter/extensions/stateful-element-convert-extension'),
              SidebarLink(text: "Stateful Widget Convert Widget Extension", href: '/packages/signals_flutter/extensions/stateful-widget-convert-widget-extension'),
              SidebarLink(text: "Stateless Element Convert Extension", href: '/packages/signals_flutter/extensions/stateless-element-convert-extension'),
              SidebarLink(text: "Stateless Widget Convert Widget Extension", href: '/packages/signals_flutter/extensions/stateless-widget-convert-widget-extension'),
              SidebarLink(text: "Value Listenable To Signal", href: '/packages/signals_flutter/extensions/value-listenable-to-signal'),
              SidebarLink(text: "Value Notifier To Signal", href: '/packages/signals_flutter/extensions/value-notifier-to-signal'),
            ],
          ),
          SidebarGroup(
            title: 'Utilities',
            links: [
              SidebarLink(text: "SignalContainer", href: '/packages/signals_flutter/utilities/container'),
              SidebarLink(text: "Model", href: '/packages/signals_flutter/utilities/model'),
              SidebarLink(text: "SignalsObserver", href: '/packages/signals_flutter/utilities/observer'),
              SidebarLink(text: "PersistedSignal", href: '/packages/signals_flutter/utilities/persisted'),
              SidebarLink(text: "SignalEquality", href: '/packages/signals_flutter/utilities/equality'),
            ],
          ),
        ],
      );
    }

    // 5. Signals Hooks Section
    if (currentUrl.startsWith('/packages/signals_hooks')) {
      return const Sidebar(
        groups: [
          SidebarGroup(
            links: [
              SidebarLink(text: "Overview & Index", href: '/packages/signals_hooks/'),
            ],
          ),

          SidebarGroup(
            title: 'Flutter Widgets',
            links: [
              SidebarLink(text: "SignalHookBuilder", href: '/packages/signals_hooks/widgets/signal-hook-builder'),
              SidebarLink(text: "SignalHookWidget", href: '/packages/signals_hooks/widgets/signal-hook-widget'),
              SidebarLink(text: "SignalStatefulHookWidget", href: '/packages/signals_hooks/widgets/signal-stateful-hook-widget'),
            ],
          ),
          SidebarGroup(
            title: 'Hooks',
            links: [
              SidebarLink(text: "useAsyncComputed", href: '/packages/signals_hooks/hooks/use-async-computed'),
              SidebarLink(text: "useAsyncSignal", href: '/packages/signals_hooks/hooks/use-async-signal'),
              SidebarLink(text: "useChangeStackSignal", href: '/packages/signals_hooks/hooks/use-change-stack-signal'),
              SidebarLink(text: "useComputed", href: '/packages/signals_hooks/hooks/use-computed'),
              SidebarLink(text: "useConnect", href: '/packages/signals_hooks/hooks/use-connect'),
              SidebarLink(text: "useExistingSignal", href: '/packages/signals_hooks/hooks/use-existing-signal'),
              SidebarLink(text: "useFutureSignal", href: '/packages/signals_hooks/hooks/use-future-signal'),
              SidebarLink(text: "useIterableSignal", href: '/packages/signals_hooks/hooks/use-iterable-signal'),
              SidebarLink(text: "useLazySignal", href: '/packages/signals_hooks/hooks/use-lazy-signal'),
              SidebarLink(text: "useLinkedSignal", href: '/packages/signals_hooks/hooks/use-linked-signal'),
              SidebarLink(text: "useListSignal", href: '/packages/signals_hooks/hooks/use-list-signal'),
              SidebarLink(text: "useMapSignal", href: '/packages/signals_hooks/hooks/use-map-signal'),
              SidebarLink(text: "useQueueSignal", href: '/packages/signals_hooks/hooks/use-queue-signal'),
              SidebarLink(text: "useSetSignal", href: '/packages/signals_hooks/hooks/use-set-signal'),
              SidebarLink(text: "useSignal", href: '/packages/signals_hooks/hooks/use-signal'),
              SidebarLink(text: "useSignalEffect", href: '/packages/signals_hooks/hooks/use-signal-effect'),
              SidebarLink(text: "useSignalProvider", href: '/packages/signals_hooks/hooks/use-signal-provider'),
              SidebarLink(text: "useSignalValue", href: '/packages/signals_hooks/hooks/use-signal-value'),
              SidebarLink(text: "useStreamSignal", href: '/packages/signals_hooks/hooks/use-stream-signal'),
              SidebarLink(text: "useTrackedSignal", href: '/packages/signals_hooks/hooks/use-tracked-signal'),
              SidebarLink(text: "useValueListenableToSignal", href: '/packages/signals_hooks/hooks/use-value-listenable-to-signal'),
              SidebarLink(text: "useValueNotifierToSignal", href: '/packages/signals_hooks/hooks/use-value-notifier-to-signal'),
            ],
          ),
        ],
      );
    }

    // 5.1. Signals DevTools Extension Section
    if (currentUrl.startsWith('/packages/signals_devtools_extension')) {
      return const Sidebar(
        groups: [
          SidebarGroup(
            links: [
              SidebarLink(text: "Overview & Index", href: '/packages/signals_devtools_extension/'),
            ],
          ),

          SidebarGroup(
            title: 'Flutter Components',
            links: [
              SidebarLink(text: "SignalsDevToolsExtension", href: '/packages/signals_devtools_extension/flutter/devtools'),
            ],
          ),
        ],
      );
    }

    // 5.2. Signals Lint Section
    if (currentUrl.startsWith('/packages/signals_lint')) {
      return const Sidebar(
        groups: [
          SidebarGroup(
            links: [
              SidebarLink(text: "Overview & Index", href: '/packages/signals_lint/'),
            ],
          ),

          SidebarGroup(
            title: 'Flutter Components',
            links: [
              SidebarLink(text: "ConvertStatefulToSignalStatefulWidget", href: '/packages/signals_lint/flutter/convert-stateful-to-signal-stateful-widget'),
              SidebarLink(text: "ConvertStatelessToSignalWidget", href: '/packages/signals_lint/flutter/convert-stateless-to-signal-widget'),
              SidebarLink(text: "MigrateSignalsMixinToSignalStatefulWidget", href: '/packages/signals_lint/flutter/migrate-signals-mixin-to-signal-stateful-widget'),
              SidebarLink(text: "MigrateWatchToSignalBuilder", href: '/packages/signals_lint/flutter/migrate-watch-to-signal-builder'),
              SidebarLink(text: "SignalsAvoidCreateInBuildMethod", href: '/packages/signals_lint/flutter/signals-avoid-create-in-build-method'),
              SidebarLink(text: "SignalsAvoidDeprecatedSignalsMixin", href: '/packages/signals_lint/flutter/signals-avoid-deprecated-signals-mixin'),
              SidebarLink(text: "SignalsAvoidDeprecatedWatchExtension", href: '/packages/signals_lint/flutter/signals-avoid-deprecated-watch-extension'),
              SidebarLink(text: "SignalsPreferNamedBuilder", href: '/packages/signals_lint/flutter/signals-prefer-named-builder'),
              SidebarLink(text: "SignalsPreferUnifiedOptions", href: '/packages/signals_lint/flutter/signals-prefer-unified-options'),
              SidebarLink(text: "WrapWithSignalBuilder", href: '/packages/signals_lint/flutter/wrap-with-signal-builder'),
            ],
          ),
        ],
      );
    }

    // 6. Unified Signals Section
    if (currentUrl.startsWith('/packages/signals')) {
      return const Sidebar(
        groups: [
          SidebarGroup(
            links: [
              SidebarLink(text: "Overview & Index", href: '/packages/signals/'),
            ],
          ),

          SidebarGroup(
            title: 'Core Primitives',
            links: [
              SidebarLink(text: "Action", href: '/packages/signals/core/action'),
              SidebarLink(text: "Batch", href: '/packages/signals/core/batch'),
              SidebarLink(text: "Signal", href: '/packages/signals/core/signal'),
              SidebarLink(text: "Computed", href: '/packages/signals/core/computed'),
              SidebarLink(text: "Effect", href: '/packages/signals/core/effect'),
              SidebarLink(text: "LinkedSignal", href: '/packages/signals/core/linked-signal'),
              SidebarLink(text: "ReadonlySignal", href: '/packages/signals/core/readonly'),
              SidebarLink(text: "Untracked", href: '/packages/signals/core/untracked'),
            ],
          ),
          SidebarGroup(
            title: 'Reactive Collections',
            links: [
              SidebarLink(text: "ChangeStackSignal", href: '/packages/signals/value/change-stack'),
              SidebarLink(text: "IterableSignal", href: '/packages/signals/value/iterable'),
              SidebarLink(text: "ListSignal", href: '/packages/signals/value/list'),
              SidebarLink(text: "MapSignal", href: '/packages/signals/value/map'),
              SidebarLink(text: "SetSignal", href: '/packages/signals/value/set'),
            ],
          ),
          SidebarGroup(
            title: 'Async Primitives',
            links: [
              SidebarLink(text: "AsyncState", href: '/packages/signals/async/state'),
              SidebarLink(text: "AsyncSignal", href: '/packages/signals/async/signal'),
              SidebarLink(text: "Computed", href: '/packages/signals/async/computed'),
              SidebarLink(text: "Connect", href: '/packages/signals/async/connect'),
              SidebarLink(text: "FutureSignal", href: '/packages/signals/async/future'),
              SidebarLink(text: "Stream", href: '/packages/signals/async/stream'),
            ],
          ),
          SidebarGroup(
            title: 'Reactive Signals',
            links: [
              SidebarLink(text: "FlutterComputed", href: '/packages/signals/signals/flutter-computed'),
              SidebarLink(text: "Flutter Readonly Signal", href: '/packages/signals/signals/flutter-readonly-signal'),
              SidebarLink(text: "FlutterSignal", href: '/packages/signals/signals/flutter-signal'),
              SidebarLink(text: "TickerSignal", href: '/packages/signals/signals/ticker-signal'),
            ],
          ),
          SidebarGroup(
            title: 'Flutter Widgets',
            links: [
              SidebarLink(text: "MultiSignalProvider", href: '/packages/signals/widgets/multi-signal-provider'),
              SidebarLink(text: "SignalAnimatedBuilder", href: '/packages/signals/widgets/signal-animated-builder'),
              SidebarLink(text: "SignalBuilder", href: '/packages/signals/widgets/signal-builder'),
              SidebarLink(text: "SignalCustomPaint", href: '/packages/signals/widgets/signal-custom-paint'),
              SidebarLink(text: "SignalPainterWidget", href: '/packages/signals/widgets/signal-painter-widget'),
              SidebarLink(text: "SignalProvider", href: '/packages/signals/widgets/signal-provider'),
              SidebarLink(text: "SignalProxyWidget", href: '/packages/signals/widgets/signal-proxy-widget'),
              SidebarLink(text: "SignalWidget", href: '/packages/signals/widgets/signal-widget'),
              SidebarLink(text: "Watch", href: '/packages/signals/widgets/watch'),
              SidebarLink(text: "WatchBuilder", href: '/packages/signals/widgets/watch-builder'),
            ],
          ),
          SidebarGroup(
            title: 'Reactive Mixins',
            links: [
              SidebarLink(text: "ChangeStackSignalMixin", href: '/packages/signals/mixins/change-stack'),
              SidebarLink(text: "EventSinkSignalMixin", href: '/packages/signals/mixins/event-sink'),
              SidebarLink(text: "IterableSignalMixin", href: '/packages/signals/mixins/iterable'),
              SidebarLink(text: "ListSignalMixin", href: '/packages/signals/mixins/list'),
              SidebarLink(text: "MapSignalMixin", href: '/packages/signals/mixins/map'),
              SidebarLink(text: "QueueSignalMixin", href: '/packages/signals/mixins/queue'),
              SidebarLink(text: "SetSignalMixin", href: '/packages/signals/mixins/set'),
              SidebarLink(text: "SignalsMixin", href: '/packages/signals/mixins/signals-mixin'),
              SidebarLink(text: "SinkSignalMixin", href: '/packages/signals/mixins/sink'),
              SidebarLink(text: "StreamSignalMixin", href: '/packages/signals/mixins/stream'),
              SidebarLink(text: "TrackedSignalMixin", href: '/packages/signals/mixins/tracked'),
              SidebarLink(text: "ValueListenableSignalMixin", href: '/packages/signals/mixins/value-listenable-signal-mixin'),
              SidebarLink(text: "ValueNotifierSignalMixin", href: '/packages/signals/mixins/value-notifier-signal-mixin'),
            ],
          ),
          SidebarGroup(
            title: 'Lifecycle & Effects',
            links: [
              SidebarLink(text: "SignalEffect", href: '/packages/signals/effects/signal-effect'),
            ],
          ),
          SidebarGroup(
            title: 'Low-Level Render Objects',
            links: [
              SidebarLink(text: "RenderSignalBox", href: '/packages/signals/render/render-signal-box'),
              SidebarLink(text: "RenderSignalCustomPaint", href: '/packages/signals/render/render-signal-custom-paint'),
              SidebarLink(text: "RenderSignalProxyBox", href: '/packages/signals/render/render-signal-proxy-box'),
            ],
          ),
          SidebarGroup(
            title: 'Widget & Context Extensions',
            links: [
              SidebarLink(text: "ConvertedSignalStatefulElement", href: '/packages/signals/extensions/converted-signal-stateful-element'),
              SidebarLink(text: "ConvertedSignalStatefulWidget", href: '/packages/signals/extensions/converted-signal-stateful-widget'),
              SidebarLink(text: "ConvertedSignalWidget", href: '/packages/signals/extensions/converted-signal-widget'),
              SidebarLink(text: "Lazy Signal", href: '/packages/signals/extensions/lazy-signal'),
              SidebarLink(text: "SignalCustomPainter", href: '/packages/signals/extensions/signal-custom-painter'),
              SidebarLink(text: "SignalElement", href: '/packages/signals/extensions/signal-element'),
              SidebarLink(text: "SignalStatefulElement", href: '/packages/signals/extensions/signal-stateful-element'),
              SidebarLink(text: "SignalStatefulWidget", href: '/packages/signals/extensions/signal-stateful-widget'),
              SidebarLink(text: "Signal Value Listenable Utils", href: '/packages/signals/extensions/signal-value-listenable-utils'),
              SidebarLink(text: "Signal Value Notifier Utils", href: '/packages/signals/extensions/signal-value-notifier-utils'),
              SidebarLink(text: "Stateful Element Convert Extension", href: '/packages/signals/extensions/stateful-element-convert-extension'),
              SidebarLink(text: "Stateful Widget Convert Widget Extension", href: '/packages/signals/extensions/stateful-widget-convert-widget-extension'),
              SidebarLink(text: "Stateless Element Convert Extension", href: '/packages/signals/extensions/stateless-element-convert-extension'),
              SidebarLink(text: "Stateless Widget Convert Widget Extension", href: '/packages/signals/extensions/stateless-widget-convert-widget-extension'),
              SidebarLink(text: "Value Listenable To Signal", href: '/packages/signals/extensions/value-listenable-to-signal'),
              SidebarLink(text: "Value Notifier To Signal", href: '/packages/signals/extensions/value-notifier-to-signal'),
            ],
          ),
          SidebarGroup(
            title: 'Utilities',
            links: [
              SidebarLink(text: "SignalContainer", href: '/packages/signals/utilities/container'),
              SidebarLink(text: "Model", href: '/packages/signals/utilities/model'),
              SidebarLink(text: "SignalsObserver", href: '/packages/signals/utilities/observer'),
              SidebarLink(text: "PersistedSignal", href: '/packages/signals/utilities/persisted'),
              SidebarLink(text: "SignalEquality", href: '/packages/signals/utilities/equality'),
            ],
          ),
        ],
      );
    }

    // Fallback Sidebar
    return const Sidebar(
      groups: [],
    );
  }
}

class Sidebar extends StatelessComponent {
  const Sidebar({this.currentRoute, required this.groups, super.key});

  final String? currentRoute;
  final List<SidebarGroup> groups;

  @override
  Component build(BuildContext context) {
    final currentUrl = currentRoute ?? context.page.url;

    String activePackageUrl;
    if (currentUrl.startsWith('/packages/signals_flutter')) {
      activePackageUrl = '/packages/signals_flutter';
    } else if (currentUrl.startsWith('/packages/signals_core')) {
      activePackageUrl = '/packages/signals_core';
    } else if (currentUrl.startsWith('/packages/preact_signals')) {
      activePackageUrl = '/packages/preact_signals';
    } else if (currentUrl.startsWith('/packages/signals_hooks')) {
      activePackageUrl = '/packages/signals_hooks';
    } else if (currentUrl.startsWith('/packages/signals_devtools_extension')) {
      activePackageUrl = '/packages/signals_devtools_extension';
    } else if (currentUrl.startsWith('/packages/signals_lint')) {
      activePackageUrl = '/packages/signals_lint';
    } else if (currentUrl.startsWith('/packages/signals')) {
      activePackageUrl = '/packages/signals';
    } else {
      activePackageUrl = '/';
    }

    return Component.fragment([
      Document.head(children: [Style(styles: _styles)]),
      nav(classes: 'sidebar', [
        button(classes: 'sidebar-close', [
          span([Component.text('✕')]),
        ]),
        select(
          classes: 'package-switcher',
          value: activePackageUrl,
          attributes: {
            'onchange': 'window.location.href = this.value',
          },
          [
            option(
              value: '/',
              selected: currentUrl == '/' || currentUrl.startsWith('/guides/') || currentUrl.startsWith('/reference/'),
              [Component.text('📖 Guides & Overview')],
            ),
            option(
              value: '/packages/signals',
              selected: currentUrl == '/packages/signals' || currentUrl.startsWith('/packages/signals/'),
              [Component.text('📦 signals')],
            ),
            option(
              value: '/packages/signals_flutter',
              selected: currentUrl == '/packages/signals_flutter' || currentUrl.startsWith('/packages/signals_flutter/'),
              [Component.text('📱 signals_flutter')],
            ),
            option(
              value: '/packages/signals_core',
              selected: currentUrl == '/packages/signals_core' || currentUrl.startsWith('/packages/signals_core/'),
              [Component.text('⚡ signals_core')],
            ),
            option(
              value: '/packages/preact_signals',
              selected: currentUrl == '/packages/preact_signals' || currentUrl.startsWith('/packages/preact_signals/'),
              [Component.text('⚛️ preact_signals')],
            ),
            option(
              value: '/packages/signals_hooks',
              selected: currentUrl == '/packages/signals_hooks' || currentUrl.startsWith('/packages/signals_hooks/'),
              [Component.text('🪝 signals_hooks')],
            ),
            option(
              value: '/packages/signals_devtools_extension',
              selected: currentUrl == '/packages/signals_devtools_extension' || currentUrl.startsWith('/packages/signals_devtools_extension/'),
              [Component.text('🛠️ signals_devtools')],
            ),
            option(
              value: '/packages/signals_lint',
              selected: currentUrl == '/packages/signals_lint' || currentUrl.startsWith('/packages/signals_lint/'),
              [Component.text('🔍 signals_lint')],
            ),
          ],
        ),
        div([
          for (final group in groups)
            div(classes: 'sidebar-group', [
              if (group.title case final groupTitle?) h3([Component.text(groupTitle)]),
              ul([
                for (final item in group.links)
                  li([
                    div(classes: currentUrl == item.href ? 'active' : null, [
                      a(href: item.href, [Component.text(item.text)]),
                    ]),
                  ]),
              ]),
            ]),
        ]),
        script(
          content: """
(function() {
  function scrollToActive() {
    var active = document.querySelector(".sidebar .active");
    if (active) {
      active.scrollIntoView({ block: "nearest", behavior: "instant" });
    }
  }
  if (document.readyState === "loading") {
    document.addEventListener("DOMContentLoaded", scrollToActive);
  } else {
    scrollToActive();
  }
  setTimeout(scrollToActive, 50);
  setTimeout(scrollToActive, 150);
})();
""",
        ),
      ]),
    ]);
  }

  static List<StyleRule> get _styles => [
    css('.sidebar', [
      css('&').styles(
        position: Position.relative(),
        fontSize: 0.875.rem,
        lineHeight: 1.25.rem,
        padding: Padding.only(left: 0.5.rem, bottom: 1.25.rem, top: 0.75.rem),
      ),
      css.media(MediaQuery.all(minWidth: 1024.px), [css('&').styles(padding: Padding.only(top: Unit.zero))]),
      css('.sidebar-close', [
        css('&').styles(
          position: Position.absolute(top: 0.75.rem, right: 0.75.rem),
        ),
        css.media(MediaQuery.all(minWidth: 1024.px), [css('&').styles(display: Display.none)]),
      ]),
      css('.sidebar-group', [
        css('&').styles(
          padding: Padding.only(top: 1.5.rem, right: 0.75.rem),
        ),
        css('h3').styles(
          fontWeight: FontWeight.w600,
          fontSize: 14.px,
          padding: Padding.only(left: 0.75.rem),
          margin: Margin.only(bottom: 1.rem, top: Unit.zero),
        ),
        css('ul').styles(listStyle: ListStyle.none, margin: Margin.zero, padding: Padding.zero),
        css('li', [
          css('div', [
            css('&').styles(
              opacity: 0.75,
              margin: Margin.only(bottom: 1.px),
              whiteSpace: WhiteSpace.noWrap,
              overflow: Overflow.hidden,
              textOverflow: TextOverflow.ellipsis,
              radius: BorderRadius.circular(.375.rem),
              display: Display.flex,
              transition: Transition('all', duration: 150.ms, curve: Curve.easeInOut),
            ),
            css('&:hover').styles(opacity: 1, backgroundColor: Color('#0000000d')),
            css('&.active').styles(
              opacity: 1,
              color: Color('#3b82f6'),
              fontWeight: FontWeight.w700,
              backgroundColor: Color('color-mix(in srgb, currentColor 15%, transparent)'),
            ),
          ]),
          css('a').styles(
            padding: Padding.only(left: 12.px, top: .5.rem, bottom: .5.rem),
            display: Display.inlineFlex,
            alignItems: AlignItems.center,
            flex: Flex(grow: 1),
          ),
        ]),
      ]),
    ]),
    css('.package-switcher', [
      css('&').styles(
        display: Display.block,
        margin: Margin.only(top: 1.5.rem, bottom: 1.rem, left: 1.rem, right: 1.rem),
        padding: Padding.only(top: 0.625.rem, bottom: 0.625.rem, left: 1.rem, right: 2.5.rem),
        fontSize: 0.875.rem,
        fontWeight: FontWeight.w600,
        radius: BorderRadius.circular(0.5.rem),
        cursor: Cursor.pointer,
        transition: Transition('all', duration: 150.ms, curve: Curve.easeInOut),
        raw: {
          'width': 'calc(100% - 2rem)',
          'appearance': 'none',
          '-webkit-appearance': 'none',
          'background-image': 'url("data:image/svg+xml;charset=utf-8,%3Csvg xmlns=\'http://www.w3.org/2000/svg\' fill=\'none\' viewBox=\'0 0 20 20\'%3E%3Cpath stroke=\'%2364748b\' stroke-linecap=\'round\' stroke-linejoin=\'round\' stroke-width=\'1.5\' d=\'m6 8 4 4 4-4\'/%3E%3C/svg%3E")',
          'background-position': 'right 0.75rem center',
          'background-repeat': 'no-repeat',
          'background-size': '1.25rem',
          'border': '1px solid var(--border, #e2e8f0)',
          'background-color': 'var(--bg-card, #ffffff)',
          'color': 'var(--text, #0f172a)',
        },
      ),
      css('&:hover').styles(
        raw: {
          'border-color': '#cbd5e1',
          'background-color': '#f8fafc',
        },
      ),
      css('&:focus').styles(
        raw: {
          'border-color': '#3b82f6',
          'box-shadow': '0 0 0 2px rgba(59, 130, 246, 0.15)',
        },
      ),
    ]),
    css('[data-theme="dark"] .package-switcher, html.dark .package-switcher', [
      css('&').styles(
        raw: {
          'border-color': '#475569',
          'background-color': '#1e293b',
          'color': '#f8fafc',
        },
      ),
      css('&:hover').styles(
        raw: {
          'border-color': '#64748b',
          'background-color': '#0f172a',
        },
      ),
      css('&:focus').styles(
        raw: {
          'border-color': '#3b82f6',
        },
      ),
    ]),
    css('[data-theme="dark"] .package-switcher option, html.dark .package-switcher option', [
      css('&').styles(
        raw: {
          'background-color': '#1e293b',
          'color': '#f8fafc',
        },
      ),
    ]),
  ];
}

