name: test_fixtures
version: 1.0.0
publish_to: none
resolution: workspace

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  signals:
    path: ../../signals
  signals_flutter:
    path: ../../signals_flutter
