name: Tests

on:
  pull_request:
  push:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
      - uses: dart-lang/setup-dart@v1.7.2

      - uses: subosito/flutter-action@v2.10.0
        with:
          channel: "stable"

      - name: Install melos
        run: dart pub global activate melos
      - name: Bootstrap
        run: melos bootstrap

      - name: Install dependencies
        run: melos exec --no-private flutter pub get
      
      - name: Install dependencies (signals_lint)
        run: |
          cd packages/signals_lint
          dart pub get

      - name: Analyze packages
        run: melos run analyze

      - name: Analyze signals_lint
        run: |
          cd packages/signals_lint
          dart analyze

      - name: Test packages
        run: melos run test

      - name: Test signals_lint
        run: |
          cd packages/signals_lint
          dart test
