name: Website
on:
  push:
    branches: [main]
  workflow_dispatch:

concurrency:
  group: pages
  cancel-in-progress: true

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your repository using git
        uses: actions/checkout@v6

      - name: Setup Dart SDK
        uses: dart-lang/setup-dart@v1.5.0

      - name: Setup Flutter SDK
        uses: subosito/flutter-action@v2.10.0
        with:
          channel: "stable"

      - name: Install Jaspr CLI
        run: dart pub global activate jaspr_cli

      - name: Install dependencies
        run: |
          cd docs
          flutter pub get

      - name: Build Jaspr Static Site
        run: |
          cd docs
          dart pub global run jaspr_cli:jaspr build

      - name: Upload Pages Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs/build/jaspr/

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5
